### ISSUE TITLE
Support for event based device reports from IoT SDK

### ISSUE THREAD

**Issue by chandramoulikv** [aws/aws-iot-device-sdk-java#10]
Currently the device reporting to the shadow is time-based. For e.g, the device SDK would 'sync' with the shadow based on a time-interval set using `setReportInterval(reportInterval)`. 

However, there may be cases where such time-interval based syncing is not required. 
Its possible to turn periodic syncing off by setting `reportInterval = 0`. 
But by doing so, one has to then first manually build the JSON message (including the other headers like`version, state, reported` ... ) & later may be use --
`public void update(String jsonState, long timeout)` to update the shadow.  

`private void sendDeviceReport(long reportVersion, String jsonState)` method already does the functionality of building the JSON message & updating the shadow.
It would be beneficial if a similar method is made (`public`) & is made available to use for event-based reporting.

**Comment by fengsongAWS** [comment]
Hi @chandramoulikv ,

Thanks for your interest in IoT Java SDK. You are correct! The current IoT Java SDK does not have event based reporting. Like you said, the IoT Java sdk exposes the lower implementation of shadow operation which could allow user to implement event based reporting. 

We will take your comments as a new feature request and will keep watching for this in the future. If more use cases reported, we will definitely incorporate this feature in the future release. 

Also, please feel free to let us know if you have more usage scenario and any other thoughts on IoT SDKs. 

Thanks,
Fengyi

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Device SDK in Java. We are actively working on SDK development and please let us know if you have more questions and comments. Also, please open another thread if you still have questions.
