### ISSUE TITLE
Is there any way to set userName and password to Mqtt options?

### ISSUE THREAD

**Issue by solitardj9** [aws/aws-iot-device-sdk-java#101]
I was using eclipse.paho(Java) with Open Source Mqtt Brokers.

And now I try to use AWS IoT with AWS IoT SDK(Java).

Import my project to AWS IoT Platform.

I have used Mqtt option with userName, password  before.

But in Java SDK, I can't find any interface to set them.

In the Python SDK, I can find the inteface.
(https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/html/index.html?highlight=username#AWSIoTPythonSDK.MQTTLib._AWSIoTMQTTDelegatingClient.configureUsernamePassword)

Is there any way or plan to set userName, password?

**Comment by justinboswell** [comment]
Because the AWS IoT service does not use username/password for authentication (mTLS or AWS key auth are the only authentication methods), there is no need to set these fields, they are unused by the service, nor would they be available to any listening backend service. As such, they are not exposed to client code.

**Comment by ap55** [comment]
https://aws.amazon.com/about-aws/whats-new/2019/11/aws-iot-core-makes-it-easier-to-transform-from-self-managed-to-fully-managed-aws-iot-services/

**Comment by graebm** [comment]
The [Version 2 SDK](https://github.com/aws/aws-iot-device-sdk-java/issues/101) supports custom username and password

**Comment by devCracker** [comment]
is it still same in 2022, can we connect to AWS MQTT server from iOS AWS SDK with username and password.. AWSIOTDataManager is not having a method to connect like that
