### ISSUE TITLE
How setReportInterval() works?

### ISSUE THREAD

**Issue by babbarkrishan** [aws/aws-iot-device-sdk-java#102]
I just want to understand setReportInterval() behavior. 
Suppose i give 10000 in setReportInterval(), and data is coming every 6 seconds. Would it update few packets only or no packet will get updated in shadow?
**Scenario 1**
10.00 - Packet1 (Updated in Shadow at 10.00)
10.06 - Packet2 (Updated in Shadow at 10.10)
10.12 - Packet3 (Not updated)
10.18 - Packet4 (Updated in Shadow at 10.20)
10.24 - Packet5 (Not updated)
10.30 - Packet6 (Updated in Shadow at 10.30)

**Scenario 2**
10.00 - Packet1 (Supposed to get updated at 10.10 [After 10 seconds due to setReportInterval(10000)], but before that we get another packet)
10.06 - Packet2 (Supposed to get updated at 10.16, but before that we get another packet)
10.12 - Packet3 (Supposed to get updated at 10.22, but before that we get another packet)
10.18 - Packet4 (Supposed to get updated at 10.28, but before that we get another packet)
and so on. At the end nothing is updated in shadow.

Please guide which scenario is correct. Or let me know the correct way of setReportInterval(10000) in case both scenarios are wrong.

Really appreciate your help.

Regards,
Krishan

**Comment by ColdenCullen** [comment]
If you look at `reportInterval`, it's used like this:
```java
        syncTask = client.scheduleRoutineTask(new Runnable() {
            @Override
            public void run() {
                if (!isCommandReady(Command.UPDATE)) {
                    LOGGER.fine("Device not ready for reporting");
                    return;
                }
                
                long reportVersion = localVersion.get();
                if (enableVersioning && reportVersion < 0) {
                    // if versioning is enabled, synchronize the version first
                    LOGGER.fine("Starting version sync");
                    startVersionSync();
                    return;
                }

                String jsonState = onDeviceReport();
                if (jsonState != null) {
                    LOGGER.fine("Sending device report");
                    sendDeviceReport(reportVersion, jsonState);
                }
            }
        }, 0l, reportInterval);
```

It appears to me as though this sets how frequently the shadow is synced back to the service, and has nothing to do with how frequently it retreives data from the service. Does that make sense?
