### ISSUE TITLE
No 1.3.1 JAR File on Maven Repository

### ISSUE THREAD

**Issue by shahtanay** [aws/aws-iot-device-sdk-java#103]
I am unable to download the necessary dependencies for Version 1.3.1 because there is no JAR file for the same on Maven Repository. I have it downloaded through Maven on my Macbook but am unable to repeat the same process on a Linux machine. Any help would be appreciated.

<img width="737" alt="Screen Shot 2019-06-11 at 5 02 27 PM" src="https://user-images.githubusercontent.com/30461100/59314619-f79a0900-8c6a-11e9-8c6a-1a8bb6389a08.png">

**Comment by bretambrose** [comment]
Thanks for bringing this to our attention; not sure why or how this happened.  We are in the process of putting together a 1.3.2 release and hopefully that will resolve this.

**Comment by shahtanay** [comment]
Any update on this?

**Comment by bretambrose** [comment]
We've had some internal build pipeline issues that we're still working through.  Hoping to have the source pushed this week and the maven push ironed out early next week.

**Comment by bretambrose** [comment]
1.3.2 should be in maven central now.
