### ISSUE TITLE
Where to put the certificate bks file in Project

### ISSUE THREAD

**Issue by debajyotibasak** [aws/aws-iot-device-sdk-java#105]
I have created a bks File but I am confused where should I keep the file in android project directory so that it can be accessed by the code 

`AWSIotKeystoreHelper.isKeystorePresent(keystorePath, keystoreName)`

How can I put the bks file in the 'data/data' directory of my app so that it can be accessed by the `getFilesDir().getPath()`

**Comment by bretambrose** [comment]
Hi,

Thanks for the trying the SDK.  I'll query internally to see if anyone has an idea, but given our lack of Android expertise, my guess is that you're likely to get a better answer querying an Android-specific forum/Q&A resource.
