### ISSUE TITLE
How to connect IoT Core from MQTT client behind HTTP Proxy 

### ISSUE THREAD

**Issue by linzhenggang** [aws/aws-iot-device-sdk-java#107]
We have devices behind HTTP Proxy(port:443 opened). We want to make these devices connect to IoT Core(a MQTT broker) and publish/subscribe MQTT message by using IoT Device SDK. 

So how should we do to config IoT Device SDK to use HTTP Proxy.

**Comment by JonathanHenson** [comment]
You'll need to use websockets with IAM credentials. Here's an example:
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java-samples/src/main/java/com/amazonaws/services/iot/client/sample/pubSub/PublishSubscribeSample.java#L119

**Comment by linzhenggang-km** [comment]
@JonathanHenson 
Thank you for you comment.
I know how to use MQTT over websockets to connect to IoT Core directly, but how can I let the SDK  connect to IoT Core through a HTTP Proxy?

**Comment by jmklix** [comment]
Are you looking for something similar to [this](https://docs.aws.amazon.com/iot/latest/developerguide/local-proxy.html)?

**Comment by e-g-hategan** [comment]
I'm running into the same issue with version 1.3.7 of the library.

My device needs to use a proxy in order to access the internet. 

Is there a way to configure `AWSIotMqttClient` to support HTTP proxies?
