### ISSUE TITLE
IAM role support missing

### ISSUE THREAD

**Issue by volphy** [aws/aws-iot-device-sdk-java#108]
I have several Java-based microservices that are running as Docker containers (ECS with EC2 instances).

It would be nice if AWS IoT Device SDK for Java could obtain IAM roles granted to EC2 instance and use them for authentication 
(see default AWS authentication chain: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html)

If I understand it correctly:
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java/src/main/java/com/amazonaws/services/iot/client/AWSIotMqttClient.java

either X.509 certificate or AWS Access Key (w/ AWS Secret Access Key) is need to be authenticated.

In my case, it means that I need technical IAM users instead of IAM roles (AWS Security advises using roles over users).

Is there a reason why authentication using IAM roles is not supported?

**Comment by JonathanHenson** [comment]
It's purely an oversight. I'll talk to the team on whether we'll add it here or in V2 and keep you updated.
