### ISSUE TITLE
Where to put the CA certificate in PubSub project

### ISSUE THREAD

**Issue by Akefhabbal** [aws/aws-iot-device-sdk-java#110]
Hi,

I'm using AWSIoT in my android app and I made certificates and attached policy to them, then I saved those certificates on my server, and when the app requests them I send the 3 certificates to the app which are CA, Certificate, and PrivateKey and I save them in the Keystore. The problem is when I want to save the certificates I use this funciton
`AWSIotKeystoreHelper.saveCertificateAndPrivateKey(String certId, String certPem, String keyPem,
            String keystorePath, String keystoreName, String keystorePassword)`
This function doesn't require the CA certificate why?
However, I could connect to the MQTT but with unauthenticated policy but when I attach it with authenticated policy the app cannot connect to MQTT.

Regards.

**Comment by justinboswell** [comment]
There isn't a class named ```AWSIotKeystoreHelper``` in this SDK. Is that something you got from somewhere else or built locally?

**Comment by justinboswell** [comment]
Oh I see, that is part of the [AWS Android SDK](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/mobileconnectors/iot/AWSIotKeystoreHelper.html), not the IoT Device SDK. 

You will want to open an issue on their repo [here](https://github.com/aws-amplify/aws-sdk-android).

**Comment by Akefhabbal** [comment]
Oh, sorry for the inconvenience.
