### ISSUE TITLE
Custom Health check for aws iot things

### ISSUE THREAD

**Issue by VelDeveloper** [aws/aws-iot-device-sdk-java#112]
Hi,

I am working on spring-boot 2.1 and I would like to create a custom health indicator for aws things. I have created the custom indicator but I don't know what value we have to show for IOT things.

```
@Component
public class IotHealthIndicator implements HealthIndicator {


    private final IotClient iotClient;

    public IotHealthIndicator(IotClient iotClient) {
        this.iotClient = iotClient;
    }


    @Override
    public Health health() {
        return Health.up().withDetail("iotThings",iotClient.getClass().getName()).build();
    }
}
```

**Response:**

```
{
  "status": "UP",
  "iotThings": {
    "status": "UP",
    "iot": "software.amazon.awssdk.services.iot.DefaultIotClient"
  },
  "diskSpace": {
    "status": "UP",
    "total": 250790436864,
    "free": 26796335104,
    "threshold": 10485760
  }
}
```

Here, I am using iotClient.getClass().getName() as a value instead I would like to return some useful stuff. But, I don't know what is some useful? 

Any suggestions would be really appreciable.

**Comment by graebm** [comment]
I'm confused by your code sample, based on the "software.amazon.awssdk.services.iot.DefaultIotClient" string, it looks like you're using the [AWS SDK for Java V2](https://github.com/aws/aws-sdk-java-v2). That SDK is interacting with RESTful APIs via HTTP request/response.

This Github page is for the AWS **Iot Device** SDK for Java, which is specifically for IoT devices connecting via MQTT and interacting using publish/subscribe.

In any case, you probably want to log the "Thing Name". If you have multiple devices sharing the same "thing name" you probably want to log the "client ID" that the devices use when establishing their MQTT connection.
