### ISSUE TITLE
"The security token included in the request is invalid"

### ISSUE THREAD

**Issue by aliozgun** [aws/aws-iot-device-sdk-java#114]
Hi,

I keep getting the following response along with 403 for the websocket handshake. This is the case both with ios-device-sdk 1.3.2/paho mqtt client (all the versions) and from postman too. I am including x-amz-security-token to non-canonical part of the uri as well. Authorized user's role in cognito user pool has iot:connect and policy is attached as well. Please help.

{
    "message": "The security token included in the request is invalid",
    "traceId": "0cf1774f-c070-84cf-3bcb-b470ec1736ca"
}

**Comment by bretambrose** [comment]
Could you clarify what you mean by "ios-device-sdk"?  Is that a typo?  Just want to make sure we're talking about the java iot sdk.  Also can you go into more detail about what you're trying to do (and what you're doing with postman)?  Are you able to run the related samples successfully?
