### ISSUE TITLE
AWSIotException: Too many publishes in progress (32202)

### ISSUE THREAD

**Issue by tarkal** [aws/aws-iot-device-sdk-java#115]
I know that a related issue was opened about this [here](https://github.com/aws/aws-iot-device-sdk-java/issues/33). 

However, Paho sets this value to 10 by default and offers the ability to set the value using the `setMaxInflight(int n)` method on the `MQTTConnectionsOptions` object that is passed to the `client.connect()` method. See [here](https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttConnectOptions.java#L44).

Any chance we could get access to this?

**Comment by shahtanay** [comment]
Any updates on this? I have been getting the error for too many publishes, and would like to know if we can change the default value of 10 in AWS IoT Java Device SDK 1.3.2.

**Comment by KaibaLopez** [comment]
Hi @shahtanay @tarkal,
sorry to say but this sdk is being sunsetted so there'll be no features/changes made for it, I suggest you try the [V2 ](https://github.com/aws/aws-sdk-java-v2)

**Comment by shahtanay** [comment]
Hi @KaibaLopez ,
Thanks for your prompt reply. Does the V2 have IoT capabilities? If so, I don't see how I can include the IoT device sdk dependency through Maven.

**Comment by KaibaLopez** [comment]
@shahtanay my bad, I linked the wrong sdk, [here](https://github.com/aws/aws-iot-device-sdk-java-v2), this is the correct one.
