### ISSUE TITLE
Cannot connect to IoT message broker after upgrade version 1.3.2

### ISSUE THREAD

**Issue by ufo525** [aws/aws-iot-device-sdk-java#116]
We are using AWSIOtMqttClient to connnect to IoT message broker and we are connecting using access key and secret.

The application is working fine until a recent update IoT Java SDK from 1.3.0 to 1.3.2. I started to see the below stacktrace when trying to connect to IoT message broker.

com.amazonaws.services.iot.client.AWSIotException: null
        at com.amazonaws.services.iot.client.core.AwsIotCompletion.get(AwsIotCompletion.java:213)
        at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.connect(AbstractAwsIotClient.java:178)
        at com.amazonaws.services.iot.client.AWSIotMqttClient.connect(AWSIotMqttClient.java:604)
        at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.connect(AbstractAwsIotClient.java:159)
        at com.amazonaws.services.iot.client.AWSIotMqttClient.connect(AWSIotMqttClient.java:566)

Temporary Resolution:
Downgrade to 1.3.0 solved the problem.

**Comment by ufo525** [comment]
1.3.2 is depending on eclipse paho mqtt 1.2.0, while 1.3.0 is depending on 1.1.0.

This dependency could be the root cause.

**Comment by graebm** [comment]
The paho mqtt dependency has not changed.
Both 1.3.0 and 1.3.3 of the SDK depend **exactly** on paho mqtt 1.1.0:
```
   <dependency>
      <groupId>org.eclipse.paho</groupId>
      <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
      <version>[1.1.0]</version>
    </dependency>
```

Here's a link to the diff between [1.3.0 and 1.3.3](https://github.com/aws/aws-iot-device-sdk-java/compare/v1.3.0...v1.3.2). The changes are mostly simple dependency upgrades, but we did not upgrade paho.

That said, I don't know why your project suddenly stopped working and I'm investigating...

**Comment by graebm** [comment]
I'm able to successfully run the ShadowSample using the `-awsAccessKeyId` and `-awsSecretAccessKey` options in the 1.3.3 SDK

Are you able to turn on the logger and post more info?

**Comment by ufo525** [comment]
I opened the iot device sdk from maven repository and the pom.xml is point to org.eclipse.paho version 1.2.0 (I noticed the github pom.xml is [1.1.0])

<dependency>
      <groupId>org.eclipse.paho</groupId>
      <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
      <version>1.2.0</version>
    </dependency>

**Comment by graebm** [comment]
😨
Yikes. I see the same thing, getting SDK 1.3.2 from Maven gets me the wrong Paho version.
But doing a LOCAL maven install from Github's SDK 1.3.2 gets me the correct Paho version.

I'm waiting for the guy who knows more about our Maven publish pipeline to get in, but this is terrible and we'll have it addressed as soon as we can.

If anyone has any guesses as to why our dependency version is changing in Maven, I'm all ears.

**Comment by graebm** [comment]
We're working on a new release, but won't be able to publish today.
We'll keep you updated

**Comment by bretambrose** [comment]
1.3.3 has been published to maven central.
