### ISSUE TITLE
NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.b

### ISSUE THREAD

**Issue by tunglamdev198** [aws/aws-iot-device-sdk-java#120]
PrivateKeyReader line 131.

**Comment by KaibaLopez** [comment]
When opening an issue please clarify what the problem is, what are you trying to do and how is it failing. Logs, what you've tried so far,  sdk version and sample code helps too.
