### ISSUE TITLE
Reporting of device attribute using AWSIotDevice creates a lot of traffic.

### ISSUE THREAD

**Issue by araza91** [aws/aws-iot-device-sdk-java#126]
While extending AWSIotDevice and using annotation class AWSIotDeviceProperty, the SDK calls getter methods every X milliseconds to get the latest value of the attribute. If the attribute does not change on the device, it looks the SDK is still updating the shadow with same JSON object. Using a 0 for report interval will never update the shadow.

Is there a method already in the SDK which allows to send updates to IoT shadow only when attribute changes? If not, is there a plan to support such thing for AWSIotDevice class in future?

**Comment by graebm** [comment]
There is not currently a way to report only those attributes that have changed. By default, everything is reported at a fixed interval. 

If you want to manually control when updates are sent, set the [reporting interval](http://aws-iot-device-sdk-java-docs.s3-website-us-east-1.amazonaws.com/com/amazonaws/services/iot/client/AWSIotDevice.html#setReportInterval-long-) to 0 to disable automatic reporting. When you wish to publish the latest shadow values, send them yourself. You can see some examples in the [AWSIotDevice docs](http://aws-iot-device-sdk-java-docs.s3-website-us-east-1.amazonaws.com/com/amazonaws/services/iot/client/AWSIotDevice.html). Something like:
```
String jsonDocument = awsIotDevice.get();
...
client.update(jsonDocument);
```

**Comment by araza91** [comment]
Got it, thanks.
