### ISSUE TITLE
No messages received from PublishSubscribeSample

### ISSUE THREAD

**Issue by khoobks** [aws/aws-iot-device-sdk-java#128]
Hi,

I was hoping to get some assistance in figuring out why I am not receiving any messages from a subscribed topic. I have tried the PublishSubscribeSample code with no changes and I am not receiving any messages.

**Environment**:
Java version
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
```

Operating System
```
macOS Catalina
Version 10.15.2
```

I can confirm that, 
* I can see the published messages on the AWS MQTT Client in a web browser.
* using the Python SDK I can receive the messages published by the Java SDK.
* I have not (to my knowledge) added the Root CA (AmazonRootCA1.pem) to the OS or anywhere accessible by the sample application.
* I am using an ATS signed endpoint.
* I am running the sample application directly from `aws-iot-device-sdk-java-samples-1.3.4.jar`. There is no custom code.

I have attached a log file which will hopefully offer some clues.
[pubsub.log](https://github.com/aws/aws-iot-device-sdk-java/files/4070628/pubsub.log)

**Comment by bretambrose** [comment]
You appear to be using websockets on Java.  When you monitor the running Java sample via Python, are you using websockets and the same credentials?  

This is very strange and my first guess would be permission-policy-related.  If your python monitor is using the same creds, that would seem to rule permissions out.

**Comment by khoobks** [comment]
Hi @bretambrose 

Thanks for the clue. I reviewed the policies and I was missing the "iot:Receive" policy. Once I added that policy I started to receive messages.

Thanks
