### ISSUE TITLE
ClassNotFoundException: com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample

### ISSUE THREAD

**Issue by kuncao** [aws/aws-iot-device-sdk-java#13]
https://us-west-2.console.aws.amazon.com/iotv2/home?region=us-west-2#/connectdevice/

To configure and test the device, perform the following steps.

Step 1: Unzip the connection kit on the device
unzip connect_device_package.zip
Step 2: Add execution permissions
chmod +x start.sh
Step 3: Run the start script. Messages from your thing will appear below
./start.sh

when  run the ./start.sh
....
Downloaded: http://repo2.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo2.maven.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar (0 B at 0.0 KB/sec)
[WARNING] 
java.lang.ClassNotFoundException: com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
        at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 56.256 s
[INFO] Finished at: 2016-12-19T15:56:43+08:00
[INFO] Final Memory: 16M/130M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (default-cli) on project aws-iot-device-sdk-java-samples: An exception occured while executing the Java class. com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by liuszeng** [comment]
Hi @kuncao ,

Thank you very much for your interest in AWS IoT Java SDK!

There are two lines in the output log that look suspicious:

    ...
    Downloaded: http://repo2.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar (0 B at 0.0 KB/sec)
    Downloaded: http://repo2.maven.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar (0 B at 0.0 KB/sec)
    ...

It seems that the some of the dependencies did not get pulled down correctly to run the SDK sample. Can you verify the network connectivity and try it again? Also, can you confirm on the version of Maven you are using?

Thanks,
Liusu

**Comment by kuncao** [comment]
@liuszeng 
Thank you for help
szv1000082893:/home/awskey # mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /home/awskey/maven
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /home/awskey/jdk1.8.0_92/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.0.76-0.11-default", arch: "amd64", family: "unix"

When I change mirror to 
 <mirror>
        <id>nexus-aliyun</id>
        <mirrorOf>*</mirrorOf>
        <name>Nexus aliyun</name>
        <url>http://maven.aliyun.com/nexus/content/groups/public</url>
     </mirror>
can not copile the project sucessful

**Comment by kuncao** [comment]
.....
Downloaded: http://maven.aliyun.com/nexus/content/groups/public/org/apache/maven/maven-plugin-api/2.2.1/maven-plugin-api-2.2.1.jar (13 KB at 3.3 KB/sec)
Downloading: http://maven.aliyun.com/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
Downloaded: http://maven.aliyun.com/nexus/content/groups/public/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar (14 KB at 3.6 KB/sec)
......
Downloaded: http://maven.aliyun.com/nexus/content/groups/public/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar (14 KB at 3.6 KB/sec)
Downloading: http://maven.aliyun.com/nexus/content/groups/public/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
Downloaded: http://maven.aliyun.com/nexus/content/groups/public/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar (28 KB at 7.3 KB/sec)
....
Downloaded: http://maven.aliyun.com/nexus/content/groups/public/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar (324 KB at 67.7 KB/sec)
Downloaded: http://maven.aliyun.com/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar (238 KB at 40.0 KB/sec)
[WARNING] 
java.lang.ClassNotFoundException: com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
        at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:32 min
[INFO] Finished at: 2016-12-20T08:49:27+08:00
[INFO] Final Memory: 15M/116M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (default-cli) on project aws-iot-device-sdk-java-samples: An exception occured while executing the Java class. com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by johnrotach** [comment]
Hello @kuncao,

One thing to try to start from a clean install of the SDK. This can be done by removing the aws-iot-device-sdk-java directory and its contents and then running the start.sh script again. If this causes the same error can you post the full output of the maven build?

Thank you for using AWS IoT.

John

**Comment by bwilly** [comment]
I, too, am having the very same problem.

**Comment by fengsongAWS** [comment]
Hi @kuncao , @bwilly ,

I am not able to duplicate your problem. The start.sh works fine on my local machine. One thing you can try is to install AWS IoT Java SDK from source. The Github link is [here](https://github.com/aws/aws-iot-device-sdk-java). The README contains detailed instruction of different ways to install Java SDK. You could start from there and see if that works for you. Once it works, we can compare the outputs and difference and see the root cause. 

Hope this helps,
Fengyi

**Comment by sreedharp1** [comment]
I had the same problem. As suggested by @johnrotach, removed the aws-iot-device-sdk-java directory and its contents and then running the start.sh script again, it worked.

**Comment by spbrds** [comment]
I had the same problem after a failed "start.sh" run. It failed because I didn't have a maven installation on my machine. After installing it, I ran once more the script and it failed with the described error.

After deleting the folder like @johnrotach suggested(because it was created when the script failed) it worked OK. Thanks to johnrotach (for suggesting) and sreedharp1 (for confirming it works).

**Comment by NikhilKumarM** [comment]
This issue still persists when using Java 10. I have tried above solutions. But it did not work for me. When I downgraded version to Java 8, it worked.

**Comment by Naveenkumarreddychanapathi** [comment]
pi@raspberrypi:~/AWS $ ./start.sh 

Running pub/sub sample application...
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] -----------< com.amazonaws:aws-iot-device-sdk-java-samples >------------
[INFO] Building aws-iot-device-sdk-java-samples 1.3.4
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ aws-iot-device-sdk-java-samples ---
[WARNING] 
java.lang.ClassNotFoundException: com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample
    at java.net.URLClassLoader.findClass (URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:357)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:270)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.727 s
[INFO] Finished at: 2020-02-06T11:25:24+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project aws-iot-device-sdk-java-samples: An exception occured while executing the Java class. com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by moleksyuk** [comment]
Same for me, works only with Java 8

**Comment by aspcompiler** [comment]
I ran into the same issue today but I was able to fix it. Hope it gives a hint to problems encountered by others.

I installed maven using "brew install maven". It pulled down openjdk as a dependency. However, I was running a different JDK and hence the JDK confusion. The fix was to "brew uninstall maven" and "brew uninstall openjdk". Then I installed maven manually from the maven website. Then rebuilt/cleanup and it worked like a charm.

**Comment by twkim74** [comment]
twkim@ubuntu:~/temp/connect_device_package$ ./start.sh 

Running pub/sub sample application...
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] -----------< com.amazonaws:aws-iot-device-sdk-java-samples >------------
[INFO] Building aws-iot-device-sdk-java-samples 1.3.7
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ aws-iot-device-sdk-java-samples ---
[WARNING] 
java.lang.ClassNotFoundException: com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample
    at java.net.URLClassLoader.findClass (URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:351)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:246)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.271 s
[INFO] Finished at: 2021-01-18T23:06:42-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project aws-iot-device-sdk-java-samples: An exception occured while executing the Java class. com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

twkim@ubuntu:~/temp/connect_device_package$ mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_275, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-39-generic", arch: "amd64", family: "unix"


The same issue isn't resolved after downgrading to Java 8, for me...

I'd appreciate you if you give any help to me...

**Comment by twkim74** [comment]
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Subscribe",
        "iot:Connect",
        "iot:Receive"
      ],
      "Resource": "*"
    }
  ]
}

Resource of Policy is revised like above... and it works!!

**Comment by technghiath** [comment]
@twkim74 
Try suggestion below:
> I had the same problem. As suggested by @johnrotach, removed the aws-iot-device-sdk-java directory and its contents and then running the start.sh script again, it worked.
It worked for me

**Comment by brijeshkundu** [comment]
The default tutorial on the AWS IOT gives this error with the latest 1.3.9 aws-iot-device-sdk-java jar configured in the pom.xml file. It worked for me when I went to pom.xml under aws-iot-device-sdk-java-samples folder and changed the version under
<artifactId>aws-iot-device-sdk-java</artifactId> from 1.3.9 to 1.3.0. 
Amazon needs to fix the jar or fix the tutorial.

**Comment by DALDEI** [comment]
The problem is that the IOT samples have been deleted from github.
PublishSubscribeSample 
Used to be on github but was deleted.

Last tag which contained the source:


https://github.com/aws/aws-iot-device-sdk-java/blob/v1.3.8/aws-iot-device-sdk-java-samples/src/main/java/com/amazonaws/services/iot/client/sample/pubSub/PublishSubscribeSample.java
