### ISSUE TITLE
Shadow update leads to connection deadlock

### ISSUE THREAD

**Issue by jag3435** [aws/aws-iot-device-sdk-java#131]
Shadow update responds fine first time but after that seems like deadlock being created, all the communication stops but connection still reporting connected.

**Comment by KaibaLopez** [comment]
Hi @jag3435 , could you provide some sample code to reproduce this?
Also, logs you get would also help.

Thanks

**Comment by jag3435** [comment]
Hi @KaibaLopez,

I am using example code that comes with SDK. Deadlock happen when I edit shadow on IoT core directly.
It works for first time, device receives all the topic messages but when I edit again it get into dead locks. Hope this info will help you.

Thanks
Jag

**Comment by KaibaLopez** [comment]
Quick question before I go deeper into this, are you editing the shadow through "desired state"? 

I'll try and reproduce this, but in the mean time, you may also want to check out the [V2](https://github.com/aws/aws-iot-device-sdk-java-v2) of the sdk, since we wouldn't be making any big changes to this sdk anymore.

**Comment by jag3435** [comment]
Yes desires state. I played with it too.

Sure, I will check v2, is that the next version?

**Comment by KaibaLopez** [comment]
Yea, it should be easier to use too, but we don't have documentation yet so, it's really up to you which one you would rather use.

**Comment by jag3435** [comment]
Actually problem was with sync processing of shadow update that was creating a backloop deadlock.
Issue got fixed with runAsync.

**Comment by KaibaLopez** [comment]
great news, sorry I couldn't be of more help.
