### ISSUE TITLE
Callback for onConnectionClosed

### ISSUE THREAD

**Issue by jag3435** [aws/aws-iot-device-sdk-java#132]
Client exposes methods onConnectionClosed, onConnectionSuccess and onConnectionFailure. 
How to pass call back method?

Implemented AwsIotMessageCallback and created listener on AwsIotMqttConnectionListener, but its implementing AwsIotMessageCallback instead of AwsIotConnectionCallback and even does not report to overridden methods.

Really apricate any help.

**Comment by KaibaLopez** [comment]
Hi @jag3435 ,
Could you show me sample code on what you're trying to do?

**Comment by jag3435** [comment]
Hi @KaibaLopez,

I am using example code that comes with SDK. Deadlock happen when I edit shadow on IoT core directly.
It works for first time, device receives all the topic messages but when I edit again it get into dead locks. Hope this info will help you.

Thanks
Jag

**Comment by jag3435** [comment]
Hi @KaibaLopez,

    private void connectClient() throws AWSIotException {
        client.connect();
        TopicListener topic = new TopicListener(CmiCloudTopics.RECEIVE_MESSAGES_TOPIC, AWSIotQos.QOS1, clientConfig.getClientId());
        topic.getOnMessageReceived().subscribe(this::onMessageReceived);
        client.subscribe(topic);
        ShadowTopicListener topicShadow = new ShadowTopicListener(CmiCloudTopics.SHADOW_TOPIC, AWSIotQos.QOS1, clientConfig.getThingName());
        topicShadow.getOnMessageReceived().subscribe(this::onShadowUpdated);
        client.subscribe(topicShadow);
        
        //how to subscribe to closed connection event
        client.onConnectionClosed....
    }

In this code I can subscribe to topics but how I can subscribe to onConnectionClosed?
I want to know when connection is permanently closed.

**Comment by KaibaLopez** [comment]
Hi @jag3435, sorry for the delayed response
Not sure if you're still having this issue but in case you are, I think what you're looking for would be something like:
```
   client.on('close', function() {
            console.log('do something here');
         });
```

**Comment by KaibaLopez** [comment]
Hi @jag3435 ,
Sorry for the late response,I think what you're looking for is:
`awsIotClient.getConnection().onConnectionClosed();`

**Comment by jag3435** [comment]
I think from this I can get back the callback but how I can pass my call to notify my handler when connection permanently closed.

**Comment by rogue2yjg** [comment]
I have the same question~

**Comment by jag3435** [comment]
Hi Kaiba, any update?

**Comment by bretambrose** [comment]
It seems like subclassing from AWSIotMqttClient would give you what you're looking for.  Is this not the case?

**Comment by jag3435** [comment]
Can you show me little example code, sorry I am new to java world?
I tried with AwsIotMqttConnectionListener by passing the userCall back but no luck.

Thank for your help.

**Comment by bretambrose** [comment]
```
public class MyAwsIotClient extends AWSIotMqttClient {
    ... add whatever constructors you want ...

    @Override
    public void onConnectionClosed() {
        super.onConnectionClosed();
        ... do whatever you want here ...
    }
}
```
