### ISSUE TITLE
I got this error can any one solve this

### ISSUE THREAD

**Issue by Naveenkumarreddychanapathi** [aws/aws-iot-device-sdk-java#133]
pi@raspberrypi:~/AWS $ ./start.sh 

Running pub/sub sample application...
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] -----------< com.amazonaws:aws-iot-device-sdk-java-samples >------------
[INFO] Building aws-iot-device-sdk-java-samples 1.3.4
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ aws-iot-device-sdk-java-samples ---
[WARNING] 
java.lang.ClassNotFoundException: com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample
    at java.net.URLClassLoader.findClass (URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:357)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:270)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.727 s
[INFO] Finished at: 2020-02-06T11:25:24+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project aws-iot-device-sdk-java-samples: An exception occured while executing the Java class. com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by KaibaLopez** [comment]
Hi @Naveenkumarreddychanapathi ,
I see you're trying to run the pub/sub sample, but can you show what is in your start.sh? specifically how are you calling the pub/sub sample. 

Also, you may want to take a look at [V2](https://github.com/aws/aws-iot-device-sdk-java-V2).
