### ISSUE TITLE
AWSIotMqttClient support for CredentialsProvider

### ISSUE THREAD

**Issue by mygordienko** [aws/aws-iot-device-sdk-java#143]
In order to create instance of _AWSIotMqttClient_ the one have to explicitly provide certificate 
and private key (if certificate authentication is used for a device). The problem is that Mqtt cliet has 
state (subscriptions), which is supposed to be kept between connections (client code does not care about 
connection issues). But credentials may be subject to change, consider the following scenario:

Device uses two types of certificates: **bootstrap** and **main**. When connecting for the first time there is only
bootstrap certificate. After bootstrap procedure is done and device has got its main certificate, the bootstrap 
certificate can be removed.

It would be nice to have _AWSIotMqttClient_ instance created at device startup and injected it wherever needed.
The client code basicaly does not care about credentials type (bootstrap or main), it just need a client.
I could implement custom _CredentialsProvider_, which 

- search first for main certificate in dedicated location
- if failed, search for bootstrap certificate in dedicated location
- throw an error

and this is transparent for the rest of the client.

**Comment by TingDaoK** [comment]
Hi,
While we’d love PRs, we are actually sunsetting this project and only taking guidance questions here. I’d suggesting checking out our [V2](https://github.com/aws/aws-iot-device-sdk-java-v2), and making it there, it would be much more likely to be considered there.
