### ISSUE TITLE
AWS IoT Broker disconnects upon publish request

### ISSUE THREAD

**Issue by bszekely** [aws/aws-iot-device-sdk-java#144]
I have an established connection to the IoT broker endpoint (8883) through the Java SDK, I can see 3 related threads in the JVM: MQTT Rec: <clientId>, MQTT Snd: <clientId>, MQTT Call: <clientId>.
However when I call client.publish(...) using the AWSIotMqttClient, the client immediately disconnects from the broker with the following log messages:
May 16, 2020 12:15:52 AM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
May 16, 2020 12:15:52 AM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: SWS-WS-eu5mr223bfc49
May 16, 2020 12:15:55 AM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
May 16, 2020 12:15:56 AM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionSuccess
INFO: Connection successfully established
May 16, 2020 12:15:56 AM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionSuccess
INFO: Client connection active: SWS-WS-eu5mr223bfc49

The disconnection reason (captured by a presence change event with Lambda): CONNECTION_LOST

I'm establishing connection in an init method as follows:
    public void init() {
	client = new AWSIotMqttClient(MQTT_CLIENT_ENDPOINT, MQTT_CLIENT_ID + new BigInteger(64, new SecureRandom()).toString(32), readStore(), KEYPASS);
	client.setPort(8883);
    	try {
    		client.connect(5000, false);    		
    	} catch (AWSIotException e) {
    		logger.error(e);
        	throw new AppException(e);
		} catch (AWSIotTimeoutException e) {
			logger.error(e);
        	throw new AppException(e);
		}
    }

I'm trying to publish upon a webservice request, in a different method (running as a webservice endpoint code):
try {
    	AWSIotMessage message = new AWSIotMessage(topic, AWSIotQos.QOS0, commandString);
    	client.publish(message, 3000);
} catch (AWSIotException e) {
    logger.error(e);
   throw new AppException(e);
}

Topic is a short sample string: "abc"
Message is a short sample string: "efg"

Please advise what could cause the unexpected Broker disconnects.

**Comment by TingDaoK** [comment]
Hi,
Can you check your policy? If your policy haven't allowed for publish, the connection will lost and keep reconnecting once you try to publish something. Please ensure your attached [policy](https://docs.aws.amazon.com/iot/latest/developerguide/iot-policies.html) allow publish and try again.
Policy example for your reference:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:region:account:topic/samples/test"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "arn:aws:iot:region:account:topicfilter/samples/test"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:region:account:client/samples-client-id"
      ]
    }
  ]
}
```

**Comment by bszekely** [comment]
Hi,
Thanks for the reply. I will check/adjust the policy, however the message gets published (arrives in the topic), and the disconnection happens just after the successful publish.
The current policy uses wildcards to allow every operation:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}

**Comment by bszekely** [comment]
Hi,
I updated the policy, defined allowances explicitly for the client as you suggested.
The client can connect, can publish a message, but still the disconnection happens just after the publish and then reconnects almost immediately. So I can do subsequent publish-es, however there is always a disconnect/reconnect after each and every message published.

**Comment by graebm** [comment]
From what I can see, things seem fine.

Are you able to increase the [logging level](https://github.com/aws/aws-iot-device-sdk-java#enable-logging) to get more clues?

Are you able to run the [PublishSubscribeSample](https://github.com/aws/aws-iot-device-sdk-java#run-the-sample-applications) without getting disconnected? If the sample runs fine, what are the differences between what it's doing and what your app is doing?

**Comment by bszekely** [comment]
I will increase logging and get back with results, also will check the sample app.
One more info I could dig out during debugging which may be useful info: I could capture the disconnection call originating from the ClientComms.shutdownConnection() method, where the reason is: java.lang.NoSuchMethodError: org.eclipse.paho.client.mqttv3.IMqttToken.getResponse()Lorg/eclipse/paho/client/mqttv3/internal/wire/MqttWireMessage

**Comment by bszekely** [comment]
Ok, I found the root cause of the problem. There was another version of the paho library on the classpath which caused the NoSuchMethodError exception. Removing the old library solved the problem.
One suggestion to improve the AWS IoT device SDK is to make sure these errors not failing silently.
