### ISSUE TITLE
Wrong ping timer behaviour - required new version of org.eclipse.paho.client.mqttv3

### ISSUE THREAD

**Issue by sistik** [aws/aws-iot-device-sdk-java#145]
I am solving problem with disconnection from AWS after more than 24 hours online without MQTT activity.
Keep alive time is set to 31000 and report interval is set to 0.

I have found bug in function checkForActivity in class org.eclipse.paho.client.mqttv3.internal.ClientState 

Function getKeepAlive() return time in ms (miliseconds), but variable time and lastOutboundActivity are in ns (nanoseconds).
There is always negative result of substraction `getKeepAlive() - (time - lastOutboundActivity)` because of this. It is causing problem with huge amount of timer ticks planed with time 1 ms. Logging set to FINE is unusable with this amount of timer ticks.

This bug is no longer present in
```
// https://mvnrepository.com/artifact/org.eclipse.paho/org.eclipse.paho.client.mqttv3
compile group: 'org.eclipse.paho', name: 'org.eclipse.paho.client.mqttv3', version: '1.2.4'
```

The dependency should be upgraded from version 1.2.2 to 1.2.4.

**Comment by bretambrose** [comment]
We can probably do an upgrade here shortly, but if you're worried about a 24 hour idle disconnect, I vaguely recall that that's an IoT service side limit that you won't be able to do anything about.
