### ISSUE TITLE
Failed to build on Java 11.0.8

### ISSUE THREAD

**Issue by primetomas** [aws/aws-iot-device-sdk-java#146]
When trying to run the AWS IoT examples on Ubuntu 18.04 with (the default) Java 11.0.8 build fails with.
It works to run, if built with java 8, but it doesn't build with java 11. The fix is very simple though.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project aws-iot-device-sdk-java-samples: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/7/docs/api/ are in the unnamed module.
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/user/tmp/aws/iot-core-demo/java11/aws-iot-device-sdk-java/aws-iot-device-sdk-java-samples/target/apidocs' dir.

This can be fixed easily by configuring the maven javadoc plugin to java 8 source level.

Working patch (git diff):

```
diff --git a/aws-iot-device-sdk-java-samples/pom.xml b/aws-iot-device-sdk-java-samples/pom.xml
index 7f5caf9..058c8d8 100644
--- a/aws-iot-device-sdk-java-samples/pom.xml
+++ b/aws-iot-device-sdk-java-samples/pom.xml
@@ -49,6 +49,7 @@
         <version>2.10.3</version>
         <configuration>
           <excludePackageNames>*.odin.*</excludePackageNames>
+          <source>8</source>
         </configuration>
         <executions>
           <execution>
diff --git a/aws-iot-device-sdk-java/pom.xml b/aws-iot-device-sdk-java/pom.xml
index b1bddab..26a973d 100644
--- a/aws-iot-device-sdk-java/pom.xml
+++ b/aws-iot-device-sdk-java/pom.xml
@@ -91,6 +91,7 @@
         <configuration>
           <sourcePath>target/generated-sources/delombok</sourcePath>
           <excludePackageNames>*.odin.*</excludePackageNames>
+          <source>8</source>
         </configuration>
         <executions>
           <execution>
```

**Comment by jmklix** [comment]
Thanks for the fix. I run into this error when using any java version higher than 8.
