### ISSUE TITLE
Error while installing the nexus-staging-maven-plugin-1.6.3.pom by maven while building the yocto project for imx

### ISSUE THREAD

**Issue by sdikshit786** [aws/aws-iot-device-sdk-java#149]
Here is the log-

ERROR: aws-iot-device-sdk-java-1.1.1-r0 do_compile: Function failed: do_compile (log file is located at /home/sunidhi/fsl-release-bsp_mg/build-x11/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/aws-iot-device-sdk-java/1.1.1-r0/temp/log.do_compile.14916)
ERROR: Logfile of failure stored in: /home/sunidhi/fsl-release-bsp_mg/build-x11/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/aws-iot-device-sdk-java/1.1.1-r0/temp/log.do_compile.14916
Log data follows:
| DEBUG: Executing shell function do_compile
| [INFO] Scanning for projects...
| Downloading: http://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.3/nexus-staging-maven-plugin-1.6.3.pom
| 
| [ERROR] [ERROR] Some problems were encountered while processing the POMs:
| [ERROR] Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.3 @
|  @
| [ERROR] The build could not read 1 project -> [Help 1]
| [ERROR]
| [ERROR]   The project com.amazonaws:aws-iot-device-sdk-java-pom:1.1.1 (/home/sunidhi/fsl-release-bsp_mg/build-x11/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/aws-iot-device-sdk-java/1.1.1-r0/git/pom.xml) has 1 error
| [ERROR]     Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.3: Could not transfer artifact org.sonatype.plugins:nexus-staging-maven-plugin:pom:1.6.3 from/to US (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.3/nexus-staging-maven-plugin-1.6.3.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 2]
| [ERROR]
| [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
| [ERROR] Re-run Maven using the -X switch to enable full debug logging.
| [ERROR]
| [ERROR] For more information about the errors and possible solutions, please read the following articles:
| [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
| [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/sunidhi/fsl-release-bsp_mg/build-x11/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/aws-iot-device-sdk-java/1.1.1-r0/temp/log.do_compile.14916)
ERROR: Task (/home/sunidhi/fsl-release-bsp_mg/sources/meta-iot-cloud/recipes-aws/aws-iot-device-sdk-java/aws-iot-device-sdk-java_1.1.1.bb:do_compile) failed with exit code '1'

**Comment by jmklix** [comment]
Can you please include the following info so we can better help you?

**Describe the bug**
A clear and concise description of what the bug is.

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the sdk on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs/output**
Already provided

**Comment by rpcme** [comment]
@sdikshit786 please head over to github.com/aws/meta-aws and we will see what we can do to help you there.
