### ISSUE TITLE
Unable to create AWSIotMqttClient instance

### ISSUE THREAD

**Issue by azhicodan** [aws/aws-iot-device-sdk-java#15]
I'm trying to use the java sdk to connect to the aws iot. The following code line is throwing error:

`AWSIotMqttClient client = new AWSIotMqttClient(clientEndpoint, clientId, awsAccessKeyId, awsSecretAccessKey);`

Error:
java.lang.IllegalArgumentException: **_wss://a2c6oqrhqoygg.iot.us-west-2.amazonaws.com:443_**
	at org.eclipse.paho.client.mqttv3.MqttConnectOptions.validateURI(MqttConnectOptions.java:470)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:273)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:167)
	at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnection.<init>(AwsIotMqttConnection.java:49)
	at com.amazonaws.services.iot.client.core.AwsIotWebsocketConnection.<init>(AwsIotWebsocketConnection.java:40)
	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.<init>(AbstractAwsIotClient.java:74)
	at com.amazonaws.services.iot.client.AWSIotMqttClient.<init>(AWSIotMqttClient.java:156)
	at com.pramati.aws.iot.demo.testrunner.main(testrunner.java:18)

**Comment by fengsongAWS** [comment]
Hi @azhicodan ,
The error itself indicates the illegal argument exception. Could you double check the type and format of the arguments? You can find reference through API Documents [here](http://aws-iot-device-sdk-java-docs.s3-website-us-east-1.amazonaws.com/).
Also, please the region of device and your client matches each other.

Please feel free to try a simple code snippet and see if that works for you.

Thanks for you interest in AWS IoT Java SDK.
Fengyi

**Comment by azhicodan** [comment]
Hello Fengyi,

Thanks for responding.

I am actually trying a simple code snippet. I was just trying to see if I can publish a message to a particular topic using the iot java sdk. As of now, I don't have any real device connected to the aws-iot. However, I created few things directly on the iot console. And I set the state manually for each of the things.

I was able successfully get the state of each thing, and also update its state using the REST api. I used the postman client to do that. 

After this I wanted to achieve this programmatically and that is where I decided to use the java sdk. All the parameters to the constructor are of string type so I don't see a problem with the type of these parameters and for the endpoint parameter I have followed the same format as mentioned in the documentation. Though I'd double check from my side once I go back to work.

Do we have any sample project available somewhere which we can use as a reference on how to communicate with the thing shadows or publish/subscribe to the topics?

I intend to build an app where we can monitor the devices connected to iot in real time. For achieving that I'm planning to create a java web socket server. And these web socket api will in turn talk to the aws iot using the iot sdk.

Do you think it would be feasible to achieve this goal by using this SDK? 

Thanks,
Ratish

**Comment by fengsongAWS** [comment]
Hi @azhicodan ,
We do have sample Maven projects of Java SDK. The instruction could be found [here](https://github.com/aws/aws-iot-device-sdk-java#sample-applications). You can take a look at the websocket example and see if you have problems running that. 
Based on your description, I don't see anything infeasible to achieve. The IoT SDK is built for customers who wants to connect their devices communicating with AWS IoT cloud. 
Please let us know if you have other questions.
Thanks,
Fengyi

**Comment by PIsberg** [comment]
The specific problem is the format of the clientEndpoint provided as parameter. It should only be the a2c6oqrhqoygg.iot.us-west-2.amazonaws.com part of what is provided  (the "wss://" and the port ":443" should not be necessary )

**Comment by swapnilGitTest** [comment]
i am also facing the same issue, however i have given the websocket url in the format 
<account-specific-prefix>.iot.<region>.amazonaws.com , pls let me know possible solution,

Error stack:::
Exception in thread "main" java.lang.IllegalArgumentException: wss://**-**.iot.****.amazonaws.com:443
