### ISSUE TITLE
SDK 1.3.7 AWSIotMqttClient Connection, if its closed after 5 retries, how to establish connection again

### ISSUE THREAD

**Issue by viswanag** [aws/aws-iot-device-sdk-java#153]
In SDK 1.3.7, if AWS Connection is closed, then how should we enable connection ?

If we are trying to call connect method after connection is closed using the same instance of AWSIotMqttClient, the connect method call is stuck and does not give any results even after waiting for 15 mins.

**Comment by jmklix** [comment]
It should reconnect on its own after any disconnects. What happens when you don't call the connect method after a disconnect?

**Comment by viswanag** [comment]
Consider a scenario of internet drop, then we see on connection failure getting triggered for 5 times i.e.., 5 retries (the default configuration) and then  we see that on connection closed getting triggered. With this connection gets closed and never connects back even when internet connection is restored.

**Comment by jmklix** [comment]
Can you provide more information about when this is happening? 

OS/hardware? Are you running the PublishSubscribeSample.java? What error messages are you getting? How you are testing the disconnections? Any other relevant info?

**Comment by viswanag** [comment]
OS - linux 
Zulu JVM
AWS SDK Version: 1.3.7

We have disabled internet connection by disabling the data connectivity.
Once we observe the on connection close, we have enabled the internet connectivity to check for connection establishment, but we have observed that the connect call gets stuck and doesnt provide any feedback.

**Comment by jmklix** [comment]
Try setting `awsIotClient.setMaxConnectionRetries(x);` to higher than the default of 5. This should use a progressive backoff strategy to keep attempting to reconnect until it hits the limit you specified.
