### ISSUE TITLE
Add support for proxy for MQTT client connecting to AWS IoT Core

### ISSUE THREAD

**Issue by e-g-hategan** [aws/aws-iot-device-sdk-java#163]
My devices needs to use a proxy in order to access the internet which I believe is a fairly common scenario.

I thus need a way to configure `AWSIotMqttClient` with a HTTP proxy.
The implemented solution should also support Socks v4/5 proxies. 

One way is to support the [relevant system properties](https://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html). 

Authentication in my case is done via X.509 client certificates.
I'm running version 1.3.7 of the library.

Related issues:
https://github.com/aws/aws-iot-device-sdk-java/issues/107
https://github.com/aws/aws-iot-device-sdk-java/issues/49

**Comment by jmklix** [comment]
Sorry, but we are not taking anymore feature requests for this sdk. There is a [v2 version](https://github.com/aws/aws-iot-device-sdk-java-v2) that does or you can submit a PR with the requested changes.

Note: aws-iot-device-sdk-java-v2 does support proxies, but it currently does not support [Socks](https://github.com/aws/aws-iot-device-sdk-java-v2/issues/86).
