### ISSUE TITLE
Facing issue with aws-iot-device-sdk-java Library

### ISSUE THREAD

**Issue by latheefserver** [aws/aws-iot-device-sdk-java#168]
We're using AWS IOT to send the push notifications. It was working fine till June 4th , It started failing while compiling the code. We 're using below line of code to use AWS SDK. 
It was working from last 9 months, started failing from June 4th 2021.

CODE:
    compile group: 'com.amazonaws', name: 'aws-iot-device-sdk-java', version: '1.3.4'
    compile group: 'com.amazonaws', name: 'aws-iot-device-sdk-java-samples', version: '1.3.4'
    
    ERROR:
    While compiling seeing below error:
    > Could not resolve all files for configuration ':runtime'.
   > Could not resolve org.eclipse.paho:org.eclipse.paho.client.mqttv3:[1.1.0].
     Required by:
         project : > com.amazonaws:aws-iot-device-sdk-java:1.3.4
      > Failed to list versions for org.eclipse.paho:org.eclipse.paho.client.mqttv3.
         > Unable to load Maven meta-data from https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path/org/eclipse/paho/org.eclipse.paho.client.mqttv3/maven-metadata.xml.
            > Could not get resource 'https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path/org/eclipse/paho/org.eclipse.paho.client.mqttv3/maven-metadata.xml'.
               > Could not GET 'https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path/org/eclipse/paho/org.eclipse.paho.client.mqttv3/maven-metadata.xml'. Received status code 403 from server: Forbidden
      > Failed to list versions for org.eclipse.paho:org.eclipse.paho.client.mqttv3.
         > Unable to load Maven meta-data from http://repo.grails.org/grails/plugins/org/eclipse/paho/org.eclipse.paho.client.mqttv3/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
            
            
            We tried using 'aws-iot-device-sdk-java-v2' by using below code, still seeing same error.
            
            compile group: 'software.amazon.awssdk.iotdevicesdk', name: 'aws-iot-device-sdk', version: '1.3.3'
            
            ERROR: [Fatal Error] aws-iot-device-sdk-1.3.3.pom:7:3: The element type "hr" must be terminated by the matching end-tag "</hr>".
            
            Thanks,
            Latheef

**Comment by bretambrose** [comment]
I cleared my maven cache and had no issues building either of the SDKs or samples.  The error messages seem to indicate a maven server issue or a downstream package issue.  Either way, there's not much we can do.

**Comment by latheefserver** [comment]
We have cleared  the maven cache and tried to compile the code, however, we are still experiencing the issue.

**Comment by jmklix** [comment]
Closing issue, because it seams to be a server issue.
