### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Failed to construct client due to missing certificate or credentials

### ISSUE THREAD

**Issue by mvsnbharath** [aws/aws-iot-device-sdk-java#20]
I tried to run  the source code as it is given in the repository.
I generated all the keys and certificates required.
Still am getting this error.. please have a look 
PFA my screenshot of error message

![capture2](https://cloud.githubusercontent.com/assets/25760674/23738034/91ea5b4c-04bc-11e7-8a4c-7c717759b6d9.PNG)

![capture](https://cloud.githubusercontent.com/assets/25760674/23737970/380bd61e-04bc-11e7-8066-3727cc01b98b.PNG)

**Comment by fengsongAWS** [comment]
Hi @mvsnbharath ,
I saw you are trying to run the samples out of the box. If so, you can put your Full certs path in this file 
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java-samples/src/main/resources/com/amazonaws/services/iot/client/sample/sampleUtil/aws-iot-sdk-samples.properties
Note that the clientId could be any random string you use to identify MQTT connection e.g. String clientId = "client1" and it does not have to be your arn. 

Thanks

**Comment by mvsnbharath** [comment]
Hi @fengsongAWS 
Thanks for the info
Have changed the values in samples.properties and also gave Client ID a random number, it works absolutely fine now.
Thanks a ton mate.
