### ISSUE TITLE
Mqtt SSL error: No subject alternative names matching IP address

### ISSUE THREAD

**Issue by Beppux86** [aws/aws-iot-device-sdk-java#22]
Hi,
I'm using the java SDK to create an Mqtt client to publish and subscribe.
While attempting to connect, I receive the following error:
`FINE: sdk-java: connect failed: unexpected exception
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address 35.162.54.21 found
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1506)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:93)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 35.162.54.21 found
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:167)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:93)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:200)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1488)
	... 10 more`

I obtained the client certificates from the AWS thing creation procedure, and I'm using them in the sample client founded on github. Like exmplained in the guide, I'm using a clientEndpoint like `<prefix>.iot.<region>.amazonaws.com`. The example I'm using can be found at [https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java-samples/src/main/java/com/amazonaws/services/iot/client/sample/pubSub/PublishSubscribeSample.java](url)

I verified on the server certificate (via openssl) if the hostname used was supported, and i found Inc./CN=*.iot.us-west-2.amazonaws.com, that lead me to think that all is ok.

In the debugger, I followed the hostname field, and I verified that it is correctly passed to the Mqtt library.
Usually, that error is related to the use of an IP instead of an hostname, so I suppose that can be a problem to the SDK.

**Comment by liuszeng** [comment]
Hi @Beppux86 ,

Thank you very much for your interest in AWS IoT Java SDK.

Are you using self signed certificates? Can you try the following command using the same certificates and attach the output? This is helpful for us to further investigate the issue.

    openssl s_client -connect <customer endpoint>:8883 -tls1_2 -CAfile <path to Root CA cert> -cert <Path to device cert> -key <Path to device private key>

Thanks,
Liusu

**Comment by Beppux86** [comment]
Hi @liuszeng,
sorry for delay.
I'm using self signed certificate, and the output for the command you shared is the following:

```
Loading 'screen' into random state - done
CONNECTED(00000190)
depth=2 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2006 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primar
y Certification Authority - G5
verify return:1
depth=1 C = US, O = Symantec Corporation, OU = Symantec Trust Network, CN = Symantec Class 3 Secure Server CA - G4
verify return:1
depth=0 C = US, ST = Washington, L = Seattle, O = "Amazon.com, Inc.", CN = *.iot.us-west-2.amazonaws.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=Washington/L=Seattle/O=Amazon.com, Inc./CN=*.iot.us-west-2.amazonaws.com
   i:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
 1 s:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
   i:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Auth
ority - G5
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGFzCCBP+gAwIBAgIQZMBXi2J38nA12wGy3MTdlzANBgkqhkiG9w0BAQsFADB+
MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVj
IENsYXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MB4XDTE2MDkwMjAwMDAwMFoX
DTE3MDkyNDIzNTk1OVowdzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0
b24xEDAOBgNVBAcMB1NlYXR0bGUxGTAXBgNVBAoMEEFtYXpvbi5jb20sIEluYy4x
JjAkBgNVBAMMHSouaW90LnVzLXdlc3QtMi5hbWF6b25hd3MuY29tMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoi0m7i4DWCYHO6CaBtY5atYUVKSf4CcG
4tFlW7lMRf75RrXfS5btkQgjrBSPESvwhP1OatF3m/YSLJ0zHfrnG4Gn07GjDc+y
sjMosD8EWiOjRFM35vby5aDFJ8viXpAtJxRFv4kgi7pIv8CN95ekhbqdXvD1nNAd
eibt2PyJAFmC0W/OwgV5i3QzutWAhLG+982khJ4X7hDz8pp/Kys7W8ZXvx+0P558
ctFB6ZPa9x9hPhxKvRAJJuEZ8o3IqIXV2xtAAH8a4mC+SAOOUGv7/irzfeSHAX4w
Awd5Q/aBhnakGLozAc8KfQkYQKo/6+gLftwbHcttXuTd0UDE1RORaQIDAQABo4IC
ljCCApIwRQYDVR0RBD4wPIIbaW90LnVzLXdlc3QtMi5hbWF6b25hd3MuY29tgh0q
LmlvdC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbTAJBgNVHRMEAjAAMA4GA1UdDwEB
/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwYQYDVR0gBFow
WDBWBgZngQwBAgIwTDAjBggrBgEFBQcCARYXaHR0cHM6Ly9kLnN5bWNiLmNvbS9j
cHMwJQYIKwYBBQUHAgIwGQwXaHR0cHM6Ly9kLnN5bWNiLmNvbS9ycGEwHwYDVR0j
BBgwFoAUX2DPYZBV34RDFIpgKrL1evRDGO8wKwYDVR0fBCQwIjAgoB6gHIYaaHR0
cDovL3NzLnN5bWNiLmNvbS9zcy5jcmwwVwYIKwYBBQUHAQEESzBJMB8GCCsGAQUF
BzABhhNodHRwOi8vc3Muc3ltY2QuY29tMCYGCCsGAQUFBzAChhpodHRwOi8vc3Mu
c3ltY2IuY29tL3NzLmNydDCCAQMGCisGAQQB1nkCBAIEgfQEgfEA7wB2AN3rHSt6
DU+mIIuBrYFocH4ujp0B1VyIjT0RxM227L7MAAABVu0yXyMAAAQDAEcwRQIgVevF
jbmj6uV+vYImlbYXldz9BtXZ2vaUYrEv6f8GRk8CIQD16n/mdpUEOo1LZVRQqv4f
nMXk32srk/WDoYTUy+AY1AB1AKS5CZC0GFgUh7sTosxncAo8NZgE+RvfuON3zQ7I
DdwQAAABVu0yYIUAAAQDAEYwRAIgOSrZsxcwlIyAaxSOW0Q+TQ6v2jJZ9qJKaO6D
v4oJ/CUCICHk0LkiUPNne+dJQurim7luK89qc1NcNkhFmm62+p2NMA0GCSqGSIb3
DQEBCwUAA4IBAQAPNaqFIRfPrKHWyiNNvaDmCBlsBNEtg8yJuvnczQ9UNFlC9Iut
vqHZqchhNK1EeCU5wUnIM9C+F6oe95WO/l2f2GQ40WZdHtfQqFZCVj+ft5ZbaY64
fyUOMYbmHJm9/L8J2eYyhnR8PBbQbpBD509kBbeIFLxNONeF7Tn9DAvhHqy+b4Uu
gSf94zg86yoFUEYLG0bAI3ICEbwZcQXC4+2DVilATugBxehmaRHCxt/c2L5aHHN5
XJ9NPHIaOKJAZkxidDNVqvkMmFI3saHcC+jKHUj/mwDd68ebK0HOoIa/tsYqv2jY
Shec0lL0KLfTOfR4iucsTUvlKIxa5x63AGsK
-----END CERTIFICATE-----
subject=/C=US/ST=Washington/L=Seattle/O=Amazon.com, Inc./CN=*.iot.us-west-2.amazonaws.com
issuer=/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
---
No client certificate CA names sent
---
SSL handshake has read 3508 bytes and written 1672 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 58D4E9942D3572A50A3A8408D6BAC40A8AE65A27ECB81BDB210232A6248AC509
    Session-ID-ctx:
    Master-Key: A01DCF174CB22E8259E519FCA56BFF270370A6AE9834AF5C08D43D967EA3248E239AE2D73AD6BD0379EE7494B2B38C5F
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1490348436
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
closed
```

I hope this can help, thank you.

**Comment by Beppux86** [comment]
Hi @liuszeng,
sorry for delay.
I'm using self signed certificate, and the output for the command you shared is the following:

```
Loading 'screen' into random state - done
CONNECTED(00000190)
depth=2 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2006 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primar
y Certification Authority - G5
verify return:1
depth=1 C = US, O = Symantec Corporation, OU = Symantec Trust Network, CN = Symantec Class 3 Secure Server CA - G4
verify return:1
depth=0 C = US, ST = Washington, L = Seattle, O = "Amazon.com, Inc.", CN = *.iot.us-west-2.amazonaws.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=Washington/L=Seattle/O=Amazon.com, Inc./CN=*.iot.us-west-2.amazonaws.com
   i:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
 1 s:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
   i:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Auth
ority - G5
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGFzCCBP+gAwIBAgIQZMBXi2J38nA12wGy3MTdlzANBgkqhkiG9w0BAQsFADB+
MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVj
IENsYXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MB4XDTE2MDkwMjAwMDAwMFoX
DTE3MDkyNDIzNTk1OVowdzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0
b24xEDAOBgNVBAcMB1NlYXR0bGUxGTAXBgNVBAoMEEFtYXpvbi5jb20sIEluYy4x
JjAkBgNVBAMMHSouaW90LnVzLXdlc3QtMi5hbWF6b25hd3MuY29tMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoi0m7i4DWCYHO6CaBtY5atYUVKSf4CcG
4tFlW7lMRf75RrXfS5btkQgjrBSPESvwhP1OatF3m/YSLJ0zHfrnG4Gn07GjDc+y
sjMosD8EWiOjRFM35vby5aDFJ8viXpAtJxRFv4kgi7pIv8CN95ekhbqdXvD1nNAd
eibt2PyJAFmC0W/OwgV5i3QzutWAhLG+982khJ4X7hDz8pp/Kys7W8ZXvx+0P558
ctFB6ZPa9x9hPhxKvRAJJuEZ8o3IqIXV2xtAAH8a4mC+SAOOUGv7/irzfeSHAX4w
Awd5Q/aBhnakGLozAc8KfQkYQKo/6+gLftwbHcttXuTd0UDE1RORaQIDAQABo4IC
ljCCApIwRQYDVR0RBD4wPIIbaW90LnVzLXdlc3QtMi5hbWF6b25hd3MuY29tgh0q
LmlvdC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbTAJBgNVHRMEAjAAMA4GA1UdDwEB
/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwYQYDVR0gBFow
WDBWBgZngQwBAgIwTDAjBggrBgEFBQcCARYXaHR0cHM6Ly9kLnN5bWNiLmNvbS9j
cHMwJQYIKwYBBQUHAgIwGQwXaHR0cHM6Ly9kLnN5bWNiLmNvbS9ycGEwHwYDVR0j
BBgwFoAUX2DPYZBV34RDFIpgKrL1evRDGO8wKwYDVR0fBCQwIjAgoB6gHIYaaHR0
cDovL3NzLnN5bWNiLmNvbS9zcy5jcmwwVwYIKwYBBQUHAQEESzBJMB8GCCsGAQUF
BzABhhNodHRwOi8vc3Muc3ltY2QuY29tMCYGCCsGAQUFBzAChhpodHRwOi8vc3Mu
c3ltY2IuY29tL3NzLmNydDCCAQMGCisGAQQB1nkCBAIEgfQEgfEA7wB2AN3rHSt6
DU+mIIuBrYFocH4ujp0B1VyIjT0RxM227L7MAAABVu0yXyMAAAQDAEcwRQIgVevF
jbmj6uV+vYImlbYXldz9BtXZ2vaUYrEv6f8GRk8CIQD16n/mdpUEOo1LZVRQqv4f
nMXk32srk/WDoYTUy+AY1AB1AKS5CZC0GFgUh7sTosxncAo8NZgE+RvfuON3zQ7I
DdwQAAABVu0yYIUAAAQDAEYwRAIgOSrZsxcwlIyAaxSOW0Q+TQ6v2jJZ9qJKaO6D
v4oJ/CUCICHk0LkiUPNne+dJQurim7luK89qc1NcNkhFmm62+p2NMA0GCSqGSIb3
DQEBCwUAA4IBAQAPNaqFIRfPrKHWyiNNvaDmCBlsBNEtg8yJuvnczQ9UNFlC9Iut
vqHZqchhNK1EeCU5wUnIM9C+F6oe95WO/l2f2GQ40WZdHtfQqFZCVj+ft5ZbaY64
fyUOMYbmHJm9/L8J2eYyhnR8PBbQbpBD509kBbeIFLxNONeF7Tn9DAvhHqy+b4Uu
gSf94zg86yoFUEYLG0bAI3ICEbwZcQXC4+2DVilATugBxehmaRHCxt/c2L5aHHN5
XJ9NPHIaOKJAZkxidDNVqvkMmFI3saHcC+jKHUj/mwDd68ebK0HOoIa/tsYqv2jY
Shec0lL0KLfTOfR4iucsTUvlKIxa5x63AGsK
-----END CERTIFICATE-----
subject=/C=US/ST=Washington/L=Seattle/O=Amazon.com, Inc./CN=*.iot.us-west-2.amazonaws.com
issuer=/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
---
No client certificate CA names sent
---
SSL handshake has read 3508 bytes and written 1672 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 58D4E9942D3572A50A3A8408D6BAC40A8AE65A27ECB81BDB210232A6248AC509
    Session-ID-ctx:
    Master-Key: A01DCF174CB22E8259E519FCA56BFF270370A6AE9834AF5C08D43D967EA3248E239AE2D73AD6BD0379EE7494B2B38C5F
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1490348436
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
closed
```
I hope this can help, thank you.

**Comment by fengsongAWS** [comment]
Hi @Beppux86 ,
Are you following these steps when registering your own certs? 
http://docs.aws.amazon.com/iot/latest/developerguide/device-certs-your-own.html

As noted from the instructions, you still need to use AWS IoT root CA to verify the AWS IoT server even though you register your CA with IoT.

Thanks

**Comment by Beppux86** [comment]
Hi @fengsongAWS,
honestly for certificate creation I'm using the One-click certificate creation procedure from the AWS Iot Console (is signed as Recommended).
I'll try to follow the guide you linked and I'll update you if there are any changes.

**Comment by Beppux86** [comment]
Hi @fengsongAWS ,
I tried the solution proposed in the guide that you suggested, but there are not any changes.
I tried also to run the script present in connection kit, downloaded from the website, in the section configuring a device, but got the same error.

**Comment by fengsongAWS** [comment]
Hi @Beppux86 ,
Could you elaborate more on your use case? I thought you used self-signed certificate but it turns out you downloaded certs and private key directly from IoT. 

Do you have problems when you use certs, private key and root CA all downloaded from AWS IoT?

**Comment by Beppux86** [comment]
Hi @fengsongAWS,
I have tried using both types of certificates: my own and downloaded from the IoT. 
My preference is for IoT certificates.
I misunderstood when you asked about self-signed certificates, as I thought you were referring to the possibility of connecting to the websocket. 
To sum it all up: I'm trying to use the test on github with the certificates downloaded from the site, in section [create device certificate](http://docs.aws.amazon.com/iot/latest/developerguide/create-device-certificate.html), and I get the error shown at the beginning of this thread.

**Comment by Beppux86** [comment]
Apparently it was an error related to the JDK. It has been solved reinstalling the latest JDK release

**Comment by paolo-rendano** [comment]
Hi All,
I got exactly the same issue. 

I'm on osx with java:
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

1) created CA following amazon guide (set as CN my endpoint name)
2) created device certificate using the wizard and selected (set as CN "mytestcn")
3) downloaded linux/java sample zip (which contains directly my dev certificates)
4) start.sh
5) I get the java exception

Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address 52.50.28.141 found

is it related with hostname verification?

**Comment by paolo-rendano** [comment]
Ok. Solved also on my side upgrading JDK to the latest version:

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
