### ISSUE TITLE
WebSocket Response header: Incorrect connection header

### ISSUE THREAD

**Issue by smoms** [aws/aws-iot-device-sdk-java#24]
Hi,

i am following the tutorial https://github.com/aws/aws-iot-device-sdk-java/blob/master/README.md to connect from Java to IoT through MQTT over WebSocket. I am using the simple main:

    	AWSIotMqttClient client = new AWSIotMqttClient(clientEndpoint, clientId, awsAccessKeyId, awsSecretAccessKey);
			client.connect();

But i get error:
WARNING: Connect request failure
MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect connection header
....

I am using my AWS credential. My user is also admin and i have policy for full access to IoT:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "iot:*",
            "Resource": "*"
        }
    ]
}

can you pls help?
thanks lot.

**Comment by yaswanth89** [comment]
#23 Might be the issue

**Comment by smoms** [comment]
thnaks lot yaswanth89

Downgrading to following worked!

    <dependency>
	    <groupId>org.eclipse.paho</groupId>
	    <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
	    <version>1.1.0</version>
   </dependency>

**Comment by JigneshPiZone** [comment]
> thnaks lot yaswanth89
> 
> Downgrading to following worked!
> 
> ```
> <dependency>
>     <groupId>org.eclipse.paho</groupId>
>     <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
>     <version>1.1.0</version>
> ```

Which place we should add this in project?
