### ISSUE TITLE
IotDevice update shadow only on changes.

### ISSUE THREAD

**Issue by JanisPlots** [aws/aws-iot-device-sdk-java#25]
Is there a reason why device doesn't update shadow only on changes.
Seams like inefficient and implementation doesn't provide simple way to override behavior.

**Comment by fengsongAWS** [comment]
Hi @JanisPlots ,
Device shadow could listen on delta changes of shadows, right? 
Could you elaborate or give an example what you mean by saying "device doesn't update shadow only on changes"? 
Thanks,
Fengyi

**Comment by JanisPlots** [comment]
Hi

> Device shadow could listen on delta changes of shadows, right?
Yes, is there is a way with current implementation how client could report state only on changes?

**Comment by fengsongAWS** [comment]
Hi,
Could you provide an example on what you mean report state only on changes?

Thanks

**Comment by liuszeng** [comment]
Hi @JanisPlots ,

We have not heard from you for a while. We are closing the issue for now. If you have further questions, please feel free to reopen this issue or create a new thread.

Thanks,
Liusu

**Comment by KairatRakhimov** [comment]
As i understand author says about thing updating AWS IoT shadow at configured time interval, even if values are not changed.
I have just started learning AWS IoT Java SDK, and don't see any way to report update to shadow only if something is changed. Should i set report interval to 0 and call update method when required?
