### ISSUE TITLE
What is this project's relation to aws-java-sdk-iot?

### ISSUE THREAD

**Issue by tudobala** [aws/aws-iot-device-sdk-java#26]
It is not clear to me how this project relates to https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-iot

Should I build my client based on this SDK (aws-iot-device-sdk-java), or the other SDK (aws-java-sdk-iot)?

Sorry if it's a dumb question, but honestly, I am quite lost...

**Comment by fengsongAWS** [comment]
Hi @tudobala ,
Thanks for your interest in AWS IoT SDK. 
AWS Java SDK For AWS IoT is AWS SDK which uses HTTP request which does not support long-live connection for now while aws-iot-device-sdk-java is MQTT based connection, and it is long-live connection so that you can listen to topic based on subscription.

**Comment by fengsongAWS** [comment]
Hi @tudobala ,

I don't think sdk will work friendly with typical HTTP proxy. AWS IoT Device SDK applies mutual authentication mechanism which enables server name verification. And websocket on the sdk side performs Sigv4 signing. But if you implement your own HTTP proxy and have something like file descriptor to forward all the packets from one connection to another, that might work but again, it really depends on the proxy itself.

Thanks

**Comment by nitinware** [comment]
@tudobala - I am also facing the same dilemma over which one to choose 'aws-java-sdk-iot' or 'aws-iot-device-sdk-java'. I see that 'aws-java-sdk-iot' provides more features and functionalities that 'aws-iot-device-sdk-java' Were you able to make a decision on this ?

**Comment by fengsongAWS** [comment]
Hi @nitinware ,

A quick answer on this is that if you need MQTT, then choose 'aws-iot-device-sdk-java', If you do not care about long live connection and pub/sub model, then 'aws-java-sdk-iot' which is based on HTTP may work for you.

Thanks

**Comment by nitinware** [comment]
@fengsongAWS - Thanks for quick reply,  I want to go for MQTT but in 'aws-iot-device-sdk-java' library there is no support for creating thing, getting all things created so far without connecting AWSIotMqttClient with an AWSIotDevice object etc.

**Comment by fengsongAWS** [comment]
Hi @nitinware ,
You are correct that aws-iot-device-sdk-java does not have those features because they are control plane APIs while aws-iot-device-sdk-java is only data plane. The only way to call the control plane API is using aws-sdk-java because they are HTTP based.

**Comment by chaurah** [comment]
Hi @nitinware,
    The reason those features don't exist in the device sdk is because thsoe are control plane, http only operations. There are not equivalent APIs available over MQTT. The Device SDKs have explicitly been written for long lived MQTT over TLS connections and provide support only for data plane APIs.

I would advice looking into including both the libraries if you absolutely require the features of both libraries. I realize that's not the best possible solution but the Device SDKs will never have any support for APIs that are not on the data plane.

Please let us know if we can help you further.

Rahul

**Comment by swapnilGitTest** [comment]
Hi,
I have que on aws-iot-sdk, i am using it from the corporate network and it's firewwall stopping from establishing the mqtt connection, fact is company network can not open that url for me, my query is,

How can i establish the connection betwn java and aws iot (certificate and .pem)
which proxy to use? can i have sample java code for it?

Thanks in advance
