### ISSUE TITLE
Java ME SDK

### ISSUE THREAD

**Issue by bsayiner** [aws/aws-iot-device-sdk-java#3]
Hi! I'm working a project that connect to aws iot over Embedded Java J2ME. Did you a plan for release SDK for Java Me?

**Comment by liuszeng** [comment]
Hi @bsayiner ,

Unfortunately we do not support Embedded Java J2ME right now and I cannot share the details about future plans for SDK releases. We are always collecting inputs from customers and trying to make the device SDKs better. Please stay tuned.

Thanks,
Liusu
