### ISSUE TITLE
.AWSIotException: Too many publishes in progress (32202)

### ISSUE THREAD

**Issue by priyamalM** [aws/aws-iot-device-sdk-java#33]
```
com.amazonaws.services.iot.client.AWSIotException: Too many publishes in progress (32202)
        at com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnection.publishMessage(AwsIotMqttConnection.java:92)
        at com.amazonaws.services.iot.client.core.AwsIotConnection.publish(AwsIotConnection.java:161)
        at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.publish(AbstractAwsIotClient.java:186)
        at com.amazonaws.services.iot.client.AWSIotMqttClient.publish(AWSIotMqttClient.java:793)
        at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.publish(AbstractAwsIotClient.java:181)
```

this is how i'm sending messages to shadow. i'm executing the method which sends out data to the aws for 3 times without an time interval, and i'm getting this error saying too many publishes, is there a solution for this error.

                                      
                                    
                                        deviceMsg.setQos(AWSIotQos.QOS0);
					deviceMsg.setStringPayload(shadow);
					deviceMsg.setTopic(updateTopic);
					awsIotClient.publish(deviceMsg);

**Comment by hedeshianaws** [comment]
Thank you for your interest in AWS IoT. This message is coming from the Paho MQTT client which limits the maximum number of publishes being queued to the network layer. If you are sharing one MQTT client instance with multiple threads each publishing messages, you may reach the limit. Can you please clarify what you mean by "sends data ... 3 times without an time interval". Is this in a loop with no delay between these data?

**Comment by priyamalM** [comment]
what i meant was i am trying to publish data for multiple times without a regular interval inbetween them.
`awsIotClient.publish(deviceMsg);`

**Comment by hedeshianaws** [comment]
Let's start with basic troubleshooting steps. How often are you calling publish? What is your connectivity to AWS IoT (hardwired/wifi/cellular, latency, bandwidth, packet loss/reliability)?

**Comment by priyamalM** [comment]
i was publishing about 6 messages in 2 seconds.now im bundling the all the messages together instead of sending them one by one and the error is now gone. i have a wifi connection.never thought that i'd get an error cz i  have a stable internet connection.thanks for your help i think there should be a interval between publishing, i dont have a interval in between publishing in my application i thought i don't need a one because i'm using a `non blocking publish`  call

**Comment by hedeshianaws** [comment]
Glad you were able to figure out. Please let us know if you have any more questions about the Java SDK.
