### ISSUE TITLE
AWS Iot MQTT subscribe with role?

### ISSUE THREAD

**Issue by bolddp** [aws/aws-iot-device-sdk-java#37]
Hi! Our AWS support team has changed its policy, so our teams are no longer able to create users in the AWS console. All access should be handled by roles, which generally seems like a good idea.

But our backend system (hosted in AWS ECS) needs to subscribe to a MQTT topic that is used as a command channel. To establish this subscription, I'm using AWSIotMqttClient, which is my only choice for MQTT subscriptions, as far as I understand. But to establish this connection I either need AWS credentials or certificates, and to use certificates for internal communication seems like a hassle.

Do I need to try to get an exception from their new policy, so I can create users, or is there something in my reasoning that is wrong? Or is there some updates in the near future that should resolve this, e.g. AWS SDK's getting support for MQTT over roles etc.?

**Comment by liuszeng** [comment]
Hi @bolddp ,

Thank you very much for your interest in AWS IoT.

In my understanding, AWS IAM role is just a better way to manage access to your AWS resources. You should be able to request temporary IAM credentials for a specific role and use that to establish a MQTT connection to AWS IoT over WebSocket SigV4. More details can be found below:
http://docs.aws.amazon.com/general/latest/gr/aws-access-keys-best-practices.html

Another thing you can do is to use AWS Cognito, which is actually the same mechanism in the backend. You will need to create a federated identity pool, have a role with proper policies attached to it and decide how other uses would be authenticated to request the temporary identity from this pool. More details can be found below:
http://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html

In both cases, you will need to use either AWS CLI or AWS SDKs to retrieve the IAM credentials.

Hope the above helps.

Thanks,
Liusu

**Comment by bolddp** [comment]
Thx for the info!
