### ISSUE TITLE
Lombok makes source unreadable

### ISSUE THREAD

**Issue by brucej72** [aws/aws-iot-device-sdk-java#4]
While I'm sure Lombok is very clever, I don't think its a great idea to use it in the way you do in the IoT SDK in this kind of open source project. Coming to this fresh, you can't just import the project into Eclipse to see how the classes are put together. Instead, I find that nothing compiles, and I'm forced to read the pom files, and then understand how the Lombok library works to figure out that basically someone couldn't be bothered to add getter/setter methods to their classes. That's just lazy and in no way makes the code more readable or maintainable.

**Comment by rongsaws** [comment]
Lombok was intentionally left out in the samples and user facing classes, with the assumption that most people will be just using the SDK Jar as is. But you do have a point, people may want to look into the SDK and build the SDK themselves, and not all of them have the experience with Lombok. We'll update the README file to include instructions for enabling Lombok in Eclipse and similar IDEs. 

The benefits of using Lombok to reduce the amount of boilerplate code is somewhat debatable, therefore I'm not gonna go into the full length discussion here :)

Were you able to get the SDK project imported and built in Eclipse?

**Comment by brucej72** [comment]
Yes, eventually - but even that doesn't feel entirely comfortable with the odd install process for Lombok. The point about boilerplate doesn't hold true here: the base abstract classes use Lombok's magic to generate 'hidden' getters & setters but then the concrete classes that extend them override the same getter/setter with boilerplate calling the superclass! There's no gain at all here just obfuscation.

**Comment by rongsaws** [comment]
@brucej72, thank you for providing valuable feedback. We'll consider incorporating your comments/suggestions in our future release.
