### ISSUE TITLE
Option to set Max Inflight for AWS Mqtt Client

### ISSUE THREAD

**Issue by BhatNikhil** [aws/aws-iot-device-sdk-java#42]
I am using aws iot sdk on a device which needs to send out messages at a very high rate, say 100 messages per second.  

Initially I used the blocking publish(QOS 1), but I observed that it takes around 200ms for one publish which was not acceptable for my use case. Next I used the non blocking publish which gave me a performance of around 50 messages per sec, but the rest of the messages started throwing exceptions saying too many publishes.

I understand that this is a limitation caused by the default 10 maxInflight of underlying Mqtt paho client but they have provided an option to change this max inflight, wheras aws iot sdk has just absctracted it. 

I would hence like to raise an issue to be provided with such an option to set the max inflight queue size as I feel it would help achieve a way higher rate of sending messages.

**Comment by fengsongAWS** [comment]
Hi @BhatNikhil ,
Thanks for your interest in AWS IoT Device SDK in Java. 
I understand your use case now and right now, the current SDK behavior does not expose MqttConnectOptions. We will collect more usage data and keep looking into this feature.

**Comment by stevesample** [comment]
I've got the exact same issue. Currently as a workaround I'm keeping a count of how many inflight messages I have, queuing up messages on the client once the count exceeds 10, and retrying once inflight messages start returning successfully. Being able to increase the inflight limit would be a huge help.

**Comment by BhatNikhil** [comment]
I dont think you need to compromise your design for this.... Just change the max inflight value in the aws iot sdk and build your code with it... You can send thousands of messages per sec without any issues... That is what I am doing...In the end,  isn't this the best part about open source? :)

**Comment by stevesample** [comment]
Any plans to address this? I'm able to use the workaround @BhatNikhil suggested, but it would be great to have this functionality out of the box.

**Comment by jmklix** [comment]
There are no plans to add any more features to this sdk as it is being sunsetted. You can always make your own pull-request for this repo or take a look at the [v2](https://github.com/aws/aws-iot-device-sdk-java-v2) repository.
