### ISSUE TITLE
Certificate file is not found Android

### ISSUE THREAD

**Issue by yusufonderd** [aws/aws-iot-device-sdk-java#43]
I'm using this library for android. I have an all certificates but I can't implement. I need your help. 
```

        String  certificateFile = "/Users/Yusuf/AwsCert/xxxxxxxx-certificate.pem.crt"                      
        String privateKeyFile = "/Users/Yusuf/AwsCert/xxxxxxxx-private.pem.key"           
        val pair = SampleUtil.getKeyStorePasswordPair(certificateFile,privateKeyFile)
//pair object getting is null
        val client = AWSIotMqttClient(clientEndpoint, clientId, pair.keyStore, pair.keyPassword)
        client.connect()
```

I'm getting this error: 
 Private key file not found: /Users/Yusuf/AwsCert/xxxxxxxx-private.pem.key
 Certificate file: /Users/Yusuf/AwsCert/xxxxxxxx-certificate.pem.crt is not found.

Where is my mistake ?

**Comment by liuszeng** [comment]
Hi @yusufonderd ,

Thank you very much for using AWS IoT Device SDK for Java.

It seems that it is not able to locate the specified certificate and private key files. Can you double check the path of those credential files? Also, I see the following lines in SampleUtil:
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java-samples/src/main/java/com/amazonaws/services/iot/client/sample/sampleUtil/SampleUtil.java#L84
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java-samples/src/main/java/com/amazonaws/services/iot/client/sample/sampleUtil/SampleUtil.java#L109
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java-samples/src/main/java/com/amazonaws/services/iot/client/sample/sampleUtil/SampleUtil.java#L127

Was there any log output when you were experiencing the issue?

In the meantime, the Java SDK is not really aimed to be used on Android devices. We do have an SDK specifically for Android MQTT. You can check out the following link:
https://github.com/aws/aws-sdk-android/tree/master/aws-android-sdk-iot

Hope the above helps.

Thanks,
Liusu

**Comment by yusufonderd** [comment]
Hi@liuszeng 
Thanks for your response. I know Android sdk but I can't creating a Keystore. 
 Now I'm facing  
> Failed to load private key from file and Failed to load certificate file
issue. Do you have any idea about this issue?

**Comment by liuszeng** [comment]
Hi @yusufonderd ,

The instructions for setting Android SDK keystore can be found in the following link:
https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub#steps

In the meantime, your error seems to be coming from the following line:
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java-samples/src/main/java/com/amazonaws/services/iot/client/sample/sampleUtil/SampleUtil.java#L127
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java-samples/src/main/java/com/amazonaws/services/iot/client/sample/sampleUtil/SampleUtil.java#L143

It seems that the files are there but the SampleUtil is having issue in loading them. My guess would be the certificate/key file is malformed.

Let's extract out the exception message and see what actually happens. Can you provide the logs again after you do that?

Thanks,
Liusu
