### ISSUE TITLE
Jobs API Examples

### ISSUE THREAD

**Issue by nwiz9** [aws/aws-iot-device-sdk-java#44]
Are there any jobs examples available for java sdk which are similar to js sdk found here?
https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/jobs-agent.js
https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/jobs-example.js

**Comment by liuszeng** [comment]
Hi @nwiz9 ,

Thank you very much for your interest in AWS IoT Device SDK for Java. Unfortunately, we do not have the job APIs released yet. Please stay tuned for future SDK releases.

Thanks,
Liusu

**Comment by jitsunen** [comment]
Hello Liusu,

Are there any examples for using Jobs with the current SDK release?

Thanks

**Comment by graebm** [comment]
The current Java SDK does not support Jobs.

A V2 Java SDK is in development [here](https://github.com/awslabs/aws-iot-device-sdk-java-v2), and does have support for Jobs
