### ISSUE TITLE
add EndpointPattern for AWS IoT in China

### ISSUE THREAD

**Issue by hxl9654** [aws/aws-iot-device-sdk-java#46]
throws follow Exception when use "awsAccessKeyId" and "awsSecretAccessKey" to access AWS IoT in China

same issue as https://github.com/aws/aws-iot-device-sdk-java/pull/41

**Comment by hxl9654** [comment]
java.lang.IllegalArgumentException: Could not extract region from endpoint provided at com.amazonaws.services.iot.client.util.AwsIotWebSocketUrlSigner.<init>(AwsIotWebSocketUrlSigner.java:87) at com.amazonaws.services.iot.client.core.AwsIotWebsocketConnection.<init>(AwsIotWebsocketConnection.java:46) at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.<init>(AbstractAwsIotClient.java:74) at com.amazonaws.services.iot.client.AWSIotMqttClient.<init>(AWSIotMqttClient.java:156)

**Comment by hxl9654** [comment]
![default](https://user-images.githubusercontent.com/6624983/34430855-38888cec-eca4-11e7-87a2-582ed423dd10.png)

**Comment by chaurah** [comment]
Hi @hxl9654,
     Thank you for pointing this out. We are working on a new release soon and this fix will be included. I am closing this issue as there is already a pull request with a suggested fix.

Apologies for the delay in fixing this. Please do continue to send your suggestions.

Rahul
