### ISSUE TITLE
No option to use custom SSLContext/SocketFactory

### ISSUE THREAD

**Issue by AbhinavVishak** [aws/aws-iot-device-sdk-java#53]
`AWSIotTlsSocketFactory` has a constructor to use a custom `SocketFactory`, but the front end class `AWSIotMqttClient` has no constructors that use this functionality. Is it possible to create extra constructors to add this feature as in #52 ??

**Comment by liuszeng** [comment]
Hi @AbhinavVishak ,

We already had an internal tracker for the pull request you created. We will evaluate the change and include it in future releases if applicable. I will close this one and leave the pull request open till a corresponding release is made.

Thanks,
Liusu
