### ISSUE TITLE
awsIotClient.connect() failed

### ISSUE THREAD

**Issue by hxgong** [aws/aws-iot-device-sdk-java#6]
Hi

I am trying to run the PublishSubscribeSample. I set up everything in the aws-iot-sdk-samples.properties.
It failed on line 137 awsIotClient.connect();

The configuration is pretty straight forward. Could you help me check if I missed anything, please?

Sep 08, 2016 3:37:06 AM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 more

**Comment by chaurah** [comment]
Hi @hxgong,
        Can you provide some more information on how you set the sample up? Did you build everything from source or did you use the Maven package? What values did you assign to the properties?

Rahul

**Comment by hxgong** [comment]
Hi Rahul,

Thank you for helping me out.

I load the aws-iot-device-sdk-java-samples in my IDE as the maven project.
The "main" is from the com.amazonaws.services.iot.client.sample.pubSub.PublishSubscribeSample

I populated the src/main/resources/com/amazonaws/services/iot/client/sample/sampleUtil/aws-iot-sdk-samples.properties file like the following

# Client endpoint, e.g. <prefix>.iot.us-east-1.amazonaws.com
clientEndpoint=XXXXXXXXXX.iot.us-west-2.amazonaws.com

# Client ID, unique client ID per connection
clientId=XXXXXX

# Client certificate file
certificateFile=src/main/resources/Thing1_XXXXXXX-certificate.pem.crt

# Client private key file
privateKeyFile=src/main/resources/Thing1_XXXXXXX-private.pem.key

# Thing name
thingName=Thing1

**Comment by hxgong** [comment]
Do we have the dns issue with the java sdk as well? How can we properly configure it?
 
https://forums.aws.amazon.com/thread.jspa?threadID=238267

**Comment by fengsongAWS** [comment]
Hi @hxgong ,
We were not able to recreate the issue on our end following the steps you have listed out. Could you set up CloudWatch to see the server side logging information? You can see the steps to do that here http://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html. Is it possible for you to try running this sample from a different network? This would eliminate local network settings as a possible cause.
Please let us know how it goes.

Fengyi

**Comment by hxgong** [comment]
It was a policy issue. It has been resolved.
I tried to enable the cloud watch for IoT. I can see the log for the button. But I couldn't see the log for the "Thing". Do you have a document that has more details on how to setup cloud watch for IoT?

Thanks

**Comment by chaurah** [comment]
Hi @hxgong,
    You can find a reference for how to set up Cloudwatch logs for IoT [here|http://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html]. Please let us know if you are able to set the logs up using this or if you have any other questions.

Rahul

**Comment by hxgong** [comment]
Didn't see the log in cloudwatch after the IAM setup. But the connection issue is resolved.

Thank you, everyone.

**Comment by murugespandian** [comment]
@hxgong ,whats  issue in policy..?

**Comment by pjamrozowicz** [comment]
@murugespandian I know it's kinda late answer but maybe it will help someone else. I was trying to make it all work for a couple of hours now and here is why I was getting:
`Connection lost (32109) - java.io.EOFException`

If you create your Thing by hand (so not through "connect" tab), make sure to create also Policy for that Thing and then attach it to the Thing's certificate.
So after creating Thing, go to Security tab -> Policies -> Create -> Advanced mode, paste there for example:
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "iot:*"
      ],
      "Resource": [
        "*"
      ],
      "Effect": "Allow"
    }
  ]
}`

Then go to Security -> Certificates -> Select the certificate that was created for your Thing (if you don't know which one is that, just go through all of them and see which Things are attached to it) -> Policies -> Actions -> Attach Policy and select policy you've just created. It should work like a charm now!
