### ISSUE TITLE
client.update(jsonDocument);

### ISSUE THREAD

**Issue by b-madhukar** [aws/aws-iot-device-sdk-java#64]
I dint find update method in "Class AWSIotMqttClient"

But in the help document it is said you can update shadow values 

I want to update shadow values after reading json status

**Comment by hedeshianaws** [comment]
Thank you for using AWS IoT. The MQTT client class provides basic MQTT functionality. You'll need to use AWSIoTDevice class for shadows. Please take a look a the shadowEcho example:

https://github.com/aws/aws-iot-device-sdk-java/blob/5d9830bb21d167eea995dcad38e77ad6835adc7e/aws-iot-device-sdk-java-samples/src/main/java/com/amazonaws/services/iot/client/sample/shadowEcho/ShadowEchoSample.java#L99

See API documentation here: http://aws-iot-device-sdk-java-docs.s3-website-us-east-1.amazonaws.com/com/amazonaws/services/iot/client/AWSIotDevice.html

**Comment by b-madhukar** [comment]
Thank you it solved my issue


 AWSIotMqttClient client = new AWSIotMqttClient(clientEndpoint, clientId, pair.keyStore, pair.keyPassword);
	   
	    AWSIotQos qos = AWSIotQos.QOS0;
            String topicname = "my/own/topic";
            AWSIotTopic topicName = new App(topicname, qos);
       
            AWSIotDevice awsIotDevice = new AWSIotDevice("Demo");
            System.out.print(awsIotDevice.toString());
            try {
            	client.attach(awsIotDevice);
        	    client.connect();
        	    String jsonDocument = awsIotDevice.get();
        	    String newdata="{ \"state\":\r\n" + 
        	    		"\r\n" + 
        	    		"                          { \"desired\":\r\n" + 
        	    		"\r\n" + 
        	    		"                                   {\"pump\":1}\r\n" + 
        	    		"\r\n" + 
        	    		"                          }\r\n" + 
        	    		"\r\n" + 
        	    		"                 };";
        	    System.out.println(jsonDocument);
        	    String jsonState="1";
        	    awsIotDevice .update(newdata);
        	
	     } catch (AWSIotException e) {
			e.printStackTrace();
		}

**Comment by hedeshianaws** [comment]
Great! I'm glad your question was answered. I'm going to close this issue. Please feel free to open another issue if you find problems with the SDK.
