### ISSUE TITLE
how to upload certificatefile and privatefilekey to aws lambda function

### ISSUE THREAD

**Issue by b-madhukar** [aws/aws-iot-device-sdk-java#66]
I used following lines in my code and uploaded to aws lambda function
String certificateFile = "C:\\Users\\Ganesh\\eclipse-JEE\\awsPublish\\src\\Demo\\e2293989f3-certificate.pem.crt";   
 	    String privateKeyFile = "C:\\Users\\Ganesh\\eclipse-JEE\\awsPublish\\src\\Demo\\e2293989f3-private.pem.key";  
 	    
following screenshot is from AWS lambda cloud log

![capture](https://user-images.githubusercontent.com/21213986/41809152-2409fe58-7706-11e8-8539-f80e82413f23.JPG)

How can i add certificatefile and privatefilekey to my code which can be linked directly by aws lambda function?

**Comment by b-madhukar** [comment]
Lambda Client Certificate


Problem got solved 

I added files to resources folder in eclipse project.
and provided  relative path as String certificateFile "resources/certificatefilename";

Later Uploaded to AWS lambda function.

**Comment by pgiredd** [comment]
Hi Madhukar,
Can you please send me the code which you used to load certificate inside lambda?
