### ISSUE TITLE
Threads don't exit upon disconnection AWSIotMqttClient

### ISSUE THREAD

**Issue by urecsys** [aws/aws-iot-device-sdk-java#69]
After disconnecting from AWS IOT, there are still several (5) threads running.
It seems to be related to [this](https://github.com/eclipse/paho.mqtt.java/issues/402)  issue.

**The code**:
```
String certificateFile = "certificate.pem.crt";// X.509 based certificate file
String privateKeyFile = private.pem.key";// PKCS#1 or PKCS#8 PEM encoded private key file
String name= "Test";
KeyStorePasswordPair pair = SampleUtil.getKeyStorePasswordPair(certificateFile, privateKeyFile);
String clientEndpoint = "endpoint.iot.us-west-2.amazonaws.com";
AWSIotMqttClient client = new AWSIotMqttClient(clientEndpoint, name, pair.keyStore, pair.keyPassword);
client.connect();
System.out.println(client.getConnectionStatus());
client.disconnect();
System.out.println(client.getConnectionStatus());
```

**The output**:
_Cert file:certificate.pem.crt Private key: private.pem.key_
jul 12, 2018 1:10:16 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionSuccess
INFO: Connection successfully established
jul 12, 2018 1:10:16 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionSuccess
INFO: Client connection active: Test
_CONNECTED_
jul 12, 2018 1:10:16 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionClosed
INFO: Connection permanently closed
jul 12, 2018 1:10:16 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionClosed
INFO: Client connection closed: Test
_DISCONNECTED_

**The threads that are left running**:
Main at localhost:54855	
	Thread [MQTT Rec: Test] (Running)	
	Thread [MQTT Snd: Test] (Running)	
	Thread [MQTT Call: Test] (Running)	
	Thread [MQTT Disc: Test] (Running)	
	Thread [pool-1-thread-5] (Running)	
	Thread [DestroyJavaVM] (Running)

**Comment by JonathanHenson** [comment]
public void connect(long timeout, boolean blocking) throws AWSIotException, AWSIotTimeoutException {
        synchronized (this) {
            if (executionService == null) {
                executionService = Executors.newScheduledThreadPool(numOfClientThreads);
            }
        }

        AwsIotCompletion completion = new AwsIotCompletion(timeout, !blocking);
        connection.connect(completion);
        completion.get(this);
    }

the connect call spins up a thread pool. 

onConnectionClosed() shuts it down (or is supposed to). 

Which version are you using? Was it before or after the fix?

**Comment by bappelt** [comment]
I was seeing this as well, updating Paho to 1.2.1 _seems_ to have fixed it.

**Comment by valera7979** [comment]
Had the same problem with
`implementation 'com.amazonaws:aws-iot-device-sdk-java:1.3.2'
    implementation 'com.amazonaws:aws-iot-device-sdk-java-samples:1.3.2'`

works fine with 1.3.4 version
