### ISSUE TITLE
The Simplified Shadow Access Model does not support nested JSON objects.

### ISSUE THREAD

**Issue by KevinWorm** [aws/aws-iot-device-sdk-java#7]
When I partly change a nested JSON object in the desired state, the simplified shadow access model cannot correctly deserialize the corresponding delta. 

``` json
{
  "desired": {
    "foobar": {
      "foo": true,
      "bar": true
    }
  },
  "reported": {
    "foobar": {
      "foo": false,
      "bar": true
    }
  },
  "delta": {
    "foobar": {
      "foo": true
    }
  }
}
```

For the first level the SDK will use "AwsIotJsonDeserializer" to map individual fields to setters of annotated properties (@AWSIotDeviceProperty), but anything deeper will be deserialized  as a whole.

`Object value = jsonObjectMapper.treeToValue(node, field.getType());`

When a partial delta is deserialized all the fields that are not represented in the delta will contain the default values as specified in the class. This causes all kinds of problems like an endless loop where the reported state can never match the desired state.

**Comment by fengsongAWS** [comment]
Hi @KevinWorm ,
Yes, that's expected and we will update the documentation in the next release. Object deserialization may not be deterministic, as member variables may have different dependencies when used on a real device. Therefore it's recommended not to use objects but primitive types, arrays, lists and maps. If it is a pojo object, it could well be represented as a java map.
And do you have a specific use case that won't work without using nested JSON object?
Please let me know if you have further questions.
Fengyi

**Comment by KevinWorm** [comment]
Hi @fengsongAWS ,
We want to represent our device by a single shadow copy. However, it may contain a number of subdevices. This may for example be a temperature sensor (with different attributes), a pressure sensor, and a wind sensor.

Modelling all sensor attributes as top level attributes with primitive types would not be scalable for the implementation of our AWSIotDevice class, unless we model the complete device as set of multiple shadow copies, hence we would need multiple AWSIotDevice objects. 

Moreover, later in our roadmap we want the device to have a dynamic number of sub devices. If I plug in a new sensor tomorrow, how do you propose to model this at shadow copy level?

*Therefore we propose the following:*

```
AWSIotDevice {
public MyDeviceX device1;
public MyDeviceY device2;
...
}
```

Instead of calling setDevice1 if any of the values in the desired state of device1 is different from the current state, it would call device1.settAttr1 if attr1 of device1 in the desired state would be different from it's current value (available through device1.geAttr1).

Later in the roadmap we would even like to have the following:

```json
{
	"desired": {
		"devices": [{
			"x": "lorem"
		}, {
			"y": "ipsum",
			"z": "dolor"
		}]
	},
	"reported": {
		"devices": [{
			"x": "sit"
		}, {
			"y": "amet",
			"z": "dolor"
		}]
	},
	"delta": {
		"devices": [{
			"x": "lorem"
		}, {
			"y": "ipsum"
		}]
	}
}
```
would lead to
```
devices[0].setX("lorem");
devices[1].setY("ipsum");
```
but not `devices[1].setZ("dolor")`.

Even more, a day later, the device may report:
```json
{
	"reported": {
		"devices": [{
			"x": "lorem"
		}, {
			"y": "ipsum",
			"z": "dolor"
		}, {
			"a": "anotherDevice",
			"b": "pluggedIn"
		}]
	}
}
```

**Comment by fengsongAWS** [comment]
Hi @KevinWorm 
For logical (simulated) devices, what you explained about setting subdevice attributes independently may be appropriate, but it's usually not the case for real devices; we can't assume a device register can be modified without having side effects to other components or registers on the device. Therefore we pass the entire device state to the setter function, and let it make the call. Therefore, we also don't have to enforce the order of modifying these attributes.

Using array/list to model a list of devices may not always be desirable; if one of the devices somehow didn't return any reported data, it may not be added to the reported list, then all the array indexes are no longer correct. 

For these considerations and to keep simplified access model simple and less error prone, we only support top level automatic attribute deserialization; but we may consider adding support for deserializing embedded objects in the future if more use cases are found relevant.

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Device SDK in Java. We are actively working on SDK development and please let us know if you have more questions and comments. Also, please open another thread if you still have questions.
