### ISSUE TITLE
authorization error for get

### ISSUE THREAD

**Issue by deevant07** [aws/aws-iot-device-sdk-java#73]
Hi,

I am facing an policy authorization error when i call device.get(). Can someone help on this?
Error:
{
"logLevel": "ERROR",
    "status": "Failure",
    "eventType": "Publish-In",
    "protocol": "MQTT",
    "topicName": "$aws/things/HMPump/shadow/get",
    "clientId": "sdk-java",        
    "reason": "AUTHORIZATION_FAILURE"
}
Below is the code:
String shadowState = device.get();
MyDevice shadowThing = new MyDevice(thingName);
long version = AwsIotJsonDeserializer.deserializeVersion(shadowThing, shadowState); 

Policy is as follows:
<pre>
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe",
        "iot:Connect"
      ],
      "Resource": [
        "*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish"
      ],
      "Resource": [
        "arn:aws:iot:us-west-2:13341XXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update",
        "arn:aws:iot:us-west-2:13341XXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/get",
        "arn:aws:iot:us-west-2:13341XXXXtopic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/delete"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:us-west-2:13341XXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update/accepted",
        "arn:aws:iot:us-west-2:13341XXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update/rejected",
        "arn:aws:iot:us-west-2:13341XXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update/delta",
        "arn:aws:iot:us-west-2:13341XXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update/documents",
        "arn:aws:iot:us-west-2:13341XXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/get/accepted",
        "arn:aws:iot:us-west-2:13341XXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/get/rejected",
        "arn:aws:iot:us-west-2:13341XXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/delete/accepted",
        "arn:aws:iot:us-west-2:13341XXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/delete/rejected",
        "arn:aws:iot:us-west-2:13341XXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/shadow/get"
      ]
    }
  ]
}
</pre>

**Comment by JonathanHenson** [comment]
Could we get a bit more context? Such as the thing name value and how you're configuring region?

**Comment by deevant07** [comment]
ThingName : HMPump
what exactly is required in region configuration? 
The above policy is raising authorization error but if i give access to all using * then no error.

**Comment by ggthename** [comment]
Did you check the files about authorization (e.g. certificateFile or privateKeyFile ) ?
