### ISSUE TITLE
Need a tutorial to get up and running with java sdk

### ISSUE THREAD

**Issue by sushantbajra** [aws/aws-iot-device-sdk-java#8]

**Comment by fengsongAWS** [comment]
Hi @sushantbajra ,

Thanks for your interest in Iot Java Device SDK.

We have instructions here and do you have issues getting this to work?[README](https://github.com/aws/aws-iot-device-sdk-java/blob/master/README.md)

BTW, what environment are you using for running the AWS IoT Java Device SDK? The configuration might be slightly different based on the environment you choose. 

Here is a few suggestions on how to get samples running.

As suggested from the Readme instruction, here is a few things you need to check. First thing is to make sure you have java version above 1.7. Secondly, it is recommended to use IoT Device SDK for java consumed from Maven projects. If you are using IDEs like Eclipse, you could simply import aws-iot-device-sdk-java-samples as maven projects. The samples already downloaded the libraries and dependencies for you. All you need to do is having your client endpoint, certificate and private key files configured properly in aws-iot-sdk-samples.properties, which is hidded in a bunch of subfolders under src/main/resources. You could follow the link on how to create a thing in IoT condole and get those information(https://aws.amazon.com/iot/getting-started/). 



Hope this works and feel free to follow up if you still have any issues.

Thanks,
Fengyi

**Comment by sushantbajra** [comment]
@fengsongAWS  hey thanks for that. I have already read the README. Anyway I will try to do it and post a tutorial. Thanks again.

**Comment by chaurah** [comment]
Hi @sushantbajra,
     We are always interested in hearing about how we can improve the getting started experience for our SDKs. If you do feel a separate tutorial is required, please let us know as well how we can improve the documentation too. It would be very helpful. Thank you for using AWS IoT.

Rahul

**Comment by sushantbajra** [comment]
Hi @chaurah , 
Yes a separate tutorial would be very very appreciated.
