### ISSUE TITLE
Issue connecting awsIotClient

### ISSUE THREAD

**Issue by guptva5** [aws/aws-iot-device-sdk-java#80]
Hello,

I am getting bellow error while connecting client. 

1. **Code:** 
String clientEndpoint = "a2b6lf8kaverg8-ats.iot.us-west-2.amazonaws.com"; 
String clientId = "A1234567890BCDEFG"; 
String certificateFile = "/MQTT/Certificates/6e21837395-certificate.pem.crt";
String privateKeyFile = "/MQTT/Certificates/6e21837395-private.pem.key"; 
if (awsIotClient == null && certificateFile != null && privateKeyFile != null) {
	String algorithm = "RSA";

	Util.SampleUtil.KeyStorePasswordPair pair = Util.SampleUtil.getKeyStorePasswordPair(certificateFile, privateKeyFile, algorithm);

	awsIotClient = new AWSIotMqttClient(clientEndpoint, clientId, pair.keyStore, pair.keyPassword);
	try {
		awsIotClient.connect();
		System.out.println("Connection Successful!");
	} catch (AWSIotException e) {
		e.printStackTrace();
	}

2. I have not added any client from AWS Console. Rather this code is acting as client to connect to aws IOT.
3. Created certificate, but no policy. Not sure, do i require to create it or its okay to be without policy.
 
**Error:**

Nov 27, 2018 1:15:23 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 more

Nov 27, 2018 1:15:23 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Nov 27, 2018 1:15:23 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: A1234567890BCDEFG
Nov 27, 2018 1:15:26 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried

**Comment by sapher** [comment]
I had a lot of issue with this also.

This is my working code maybe it might help.

```
String certificateFile = "certificate.pem.crt";
String privateKeyFile = "private.pem.key";
SampleUtil.KeyStorePasswordPair keyStorePair = SampleUtil.getKeyStorePasswordPair(certificateFile, privateKeyFile);
AWSIotMqttClient client = new AWSIotMqttClient(clientEndpoint, clientId, keyStorePair.keyStore, keyStorePair.keyPassword);
```
