### ISSUE TITLE
Maven clean install error

### ISSUE THREAD

**Issue by Maxels88** [aws/aws-iot-device-sdk-java#82]
After I've cloned the project and attempt a maven build, I'm getting an error. Is a problem in my environment or should I be making a change with the pom.xml? Command run and response is pasted below:

PS C:\src\aws-iot-device-sdk-java> mvn clean install "-Dgpg.skip=true"
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 3 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 3 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] AWS IoT Device SDK for Java                                        [pom]
[INFO] aws-iot-device-sdk-java                                            [jar]
[INFO] aws-iot-device-sdk-java-samples                                    [jar]
[INFO]
[INFO] -------------< com.amazonaws:aws-iot-device-sdk-java-pom >--------------
[INFO] Building AWS IoT Device SDK for Java 1.2.0                         [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ aws-iot-device-sdk-java-pom ---
[INFO]
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ aws-iot-device-sdk-java-pom ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ aws-iot-device-sdk-java-pom ---
[INFO] Installing C:\src\aws-iot-device-sdk-java\pom.xml to C:\Users\mschultz\.m2\repository\com\amazonaws\aws-iot-device-sdk-java-pom\1.2.0\aws-iot-device-sdk-java-pom-1.2.0.pom
[INFO]
[INFO] ---------------< com.amazonaws:aws-iot-device-sdk-java >----------------
[INFO] Building aws-iot-device-sdk-java 1.2.0                             [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ aws-iot-device-sdk-java ---
[INFO]
[INFO] --- lombok-maven-plugin:1.16.8.0:delombok (default) @ aws-iot-device-sdk-java ---
[WARNING] Unable to detect tools.jar; java.home is C:\Program Files\Java\jdk-10.0.1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by lombok.javac.JavacTreeMaker$TypeTag to method com.sun.tools.javac.code.Type.getTag()
WARNING: Please consider reporting this to the maintainers of lombok.javac.JavacTreeMaker$TypeTag
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] AWS IoT Device SDK for Java 1.2.0 .................. SUCCESS [  2.369 s]
[INFO] aws-iot-device-sdk-java ............................ FAILURE [  2.487 s]
[INFO] aws-iot-device-sdk-java-samples 1.2.0 .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.242 s
[INFO] Finished at: 2018-12-21T09:54:15-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.projectlombok:lombok-maven-plugin:1.16.8.0:delombok (default) on project aws-iot-device-sdk-java: Unable to delombok: InvocationTargetException: ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :aws-iot-device-sdk-java

**Comment by Maxels88** [comment]
I was able to figure out there is a problem building this project with Java 10+. I switched to java 8 and it built fine. Is the lack of support for Java 10 a bug or is there no plan to support newer java versions?

**Comment by tedorian** [comment]
I have the identical error. Changing to Java 8 does not fix the problem.

**Comment by yaroslavd** [comment]
Same issue. Why isn't AWS fixing this?

**Comment by graebm** [comment]
I've made fixes in our internal repo. We'll get a new public release out soon.
