### ISSUE TITLE
Multiple clients to load balance for heavy load on same topic

### ISSUE THREAD

**Issue by guptva5** [aws/aws-iot-device-sdk-java#86]
If multiple devices sending lots of messages for backend system on same topic, how can i load balance them instead of using SQS or any other rule processing. In kafka, we do have consumer group property which make sure that clients with same consumer group should not get same message. Is there something similar in MQTT?

**Comment by justinboswell** [comment]
There is no intrinsic load balancing in the protocol or service. It would be up to whatever is subscribed to route (and potentially load balance) messages, whether that's via SQS or any other custom router.
