### ISSUE TITLE
Support Custom Authorizer

### ISSUE THREAD

**Issue by aniket91** [aws/aws-iot-device-sdk-java#87]
It does not look like current SDK support custom authorizer 
 - https://docs.aws.amazon.com/iot/latest/developerguide/custom-authorizer.html

We need to be able to set custom headers in the websocket connection and not use certificates or AWS credentials. paho mqqt client has added support for this.

**Comment by AndrewJudson** [comment]
We also have this issue. I don't think the paho version has been released yet, it says released in version 1.3.0 in this issue here, but I don't see that version out yet.  https://github.com/eclipse/paho.mqtt.java/issues/502

**Comment by mariotoffia** [comment]
Hi, has anyone looking into this? Is there some way of "hacking" the headers or otherwise have some sort of support for this in the SDK?

Cheers,
 Mario
