### ISSUE TITLE
Connect AWS IoT MQTT broker using JWT that have certificate chain

### ISSUE THREAD

**Issue by snshukla** [aws/aws-iot-device-sdk-java#88]
Hi, I have a requirement such that an application needs to connect AWS IoT MQTT broker using bearer token (JWT) that have certificate chain in it(downloaded from AWS IoT Console).

Any help to this area is highly appreciated. I am a java candidate so if possible please provide input/example using java sdk.

Thanks
snshukla

**Comment by JonathanHenson** [comment]
Have you read the documentation on the custom authorizer workflow?

https://docs.aws.amazon.com/iot/latest/developerguide/custom-auth.html

**Comment by snshukla** [comment]
Hi @JonathanHenson ,
Thanks for your input.

Yes, I have read this document but as I am new to custom authorizer so facing bit difficult to implement this in my application. 
I know about lamda function but need help about java code example that tries to connect AWS IoT which uses custom auth and execute my lamda function to authorize the connect request. 

Only way to connect AWS IoT broker that I know are as below:
1. Using certificates. 
2. Using accessKeys.

But dont know how custom auth will pe applied to connect AWS IoT broker
