### ISSUE TITLE
Disconnect after exactly 20 minutes

### ISSUE THREAD

**Issue by 20matan** [aws/aws-iot-device-sdk-java#90]
Hey, i'm really not sure why it happens...
After exactly 20 minutes of running, i get a disconnection from the process.
Also, after reading some issues with the auto-reconnect and having troubles with it myself, i tried to wrap the reconnection mechanism, and sometimes it succeeds and sometimes it fails*.

* succeeds/fail = get messages from the broker

Any ideas what's going on? my guess would be on some prop that his value should be 20 or 60*20 but i couldt find any (not in this library nor paho).

Thanks

**Comment by justinboswell** [comment]
Do you have any logs from these sessions? Could you provide more information about what you are doing/trying to do? What platform? What network infrastructure (wifi, cellular, LAN, etc)? I am not sure I understand the rest of your question after the part where you are experiencing disconnects.

**Comment by 20matan** [comment]
That's the issue, i don't have any logs, nothing about disconnection, retry or anything else
All i do is wait for messages & then create POST request to send those messages to another server, and print every minute the awsIotClient connection status which is CONNECTED.
After exactly 20 minutes, no more messages are received.
Maybe the client is disconnected after this time period, I really not sure.
This is not a one time issue, this is constantly happen from 2 different environments, computers & networks:
1 machine is in azure, and the 2nd is my local computer.

This is a really weird behavior.

To overcome it, every 10 minutes i call awsIotClient.disconnect, and i created this class which overrides the onFailure & onClose functions:

`
package com.matanp.mqtt.pubSub;

import com.amazonaws.services.iot.client.*;
import com.matanp.mqtt.utils.CommandArguments;
import com.matanp.mqtt.utils.SampleUtil;
import org.apache.log4j.Logger;
import org.json.JSONObject;

import java.security.KeyStore;

public class ExtendedIotClient extends AWSIotMqttClient {
    private static final AWSIotQos TestTopicQos = AWSIotQos.QOS0;
    final static Logger logger = Logger.getLogger(ExtendedIotClient.class);

    public ExtendedIotClient(String clientEndpoint, String clientId, KeyStore keyStore, String keyPassword) {
        super(clientEndpoint, clientId, keyStore, keyPassword);
    }

    public ExtendedIotClient(String clientEndpoint, String clientId, String awsAccessKeyId, String awsSecretAccessKey) {
        super(clientEndpoint, clientId, awsAccessKeyId, awsSecretAccessKey);
    }

    public ExtendedIotClient(String clientEndpoint, String clientId, String awsAccessKeyId, String awsSecretAccessKey, String sessionToken) {
        super(clientEndpoint, clientId, awsAccessKeyId, awsSecretAccessKey, sessionToken);
    }

    private AWSIotTopic getSubTopic() {
        String[] args = new String[0];
        CommandArguments arguments = CommandArguments.parse(args);

        logger.info("before gettnig the json file");
        String jsonFilePath = arguments.getNotNull("configFile", SampleUtil.getConfig("configFile"));

        JSONObject configJSON = SampleUtil.getFileContent(jsonFilePath);

        String thingName = configJSON.getString("thingName");
        logger.info("thingName = " + thingName);
        String environment = configJSON.getString("environment");
        logger.info("environment = " + environment);

        AWSIotTopic topic = new TestTopicListener(thingName, environment, TestTopicQos, this);

        return topic;
    }

    private void subscribe() {
        AWSIotTopic topic = this.getSubTopic();

        try {
            logger.info("beore subscribe");
            this.subscribe(topic, false);
            logger.info("subscribed succesfully");
        } catch (AWSIotException e) {
            logger.error("Error in subscribe", e);
        }
        logger.info("After subscribe");
    }

    private void unsubscribe() {
        AWSIotTopic topic = this.getSubTopic();

        logger.info("before unsubscribe");
        try {
            this.unsubscribe(topic);
            logger.info("unsubscribed succesfully");
        } catch (AWSIotException e) {
            logger.error("Error in unsubscribe", e);
        }
        logger.info("After unsubscribe");
    }

    @Override
    public void onConnectionSuccess() {
        logger.info("on custom connection success");
//        super.onConnectionSuccess();
        logger.info("called super on connection success");

        this.subscribe();
    }

    private void onError() {
        logger.info("will call this.unsubscribe()");
        this.unsubscribe();
        logger.info("succesfully called this.unsubscribe()");

        try {
            logger.info("will call this.connect()");
            this.connect(10, false);
            logger.info("succesfully called this.connect()");
        } catch (AWSIotException e) {
            logger.error("error in calling the connect", e);
        } catch (AWSIotTimeoutException e) {
            logger.error("error in calling the connect #AWSIotTimeoutException", e);
        }
    }

    @Override
    public void onConnectionFailure() {
        logger.error("connection has failed. will throw an error");

        try {
            logger.info("will call this.disconnect");
            this.disconnect();
            logger.info("will call this.disconnect");
        } catch (AWSIotException e) {
            logger.error("error onConnectionFailure - this.disconnect", e);
        }

        this.onError();
    }

    @Override
    public void onConnectionClosed() {
        logger.error("connection has closed. will throw an error");

        try {
            logger.info("will call this.disconnect");
            this.disconnect();
            logger.info("succesfully disconnected");
        } catch (AWSIotException e) {
            logger.error("error onConnectionClosed - this.disconnect", e);
        }

        this.onError();
    }
}

`

this approach is just a workaround, this is not a solution for the problem :/

**Comment by justinboswell** [comment]
What is the keepalive time set to when configuring your AwsIotMqttClient? In fact, what does your client/connection setup code look like?

Without logging, it's going to be hard to help diagnose the issue. The SDK uses the java.util.logging Logger, so make sure that isn't suppressed/disabled.

**Comment by 20matan** [comment]
i didn't change the value, left it with the default.
parts of the code (what i can share):
```
    final static int MAX_RETRIES_VALUE = 999999999;

            awsIotClient = new ExtendedIotClient(clientEndpoint, clientId, pair.keyStore, pair.keyPassword);

        awsIotClient.setMaxConnectionRetries(MAX_RETRIES_VALUE);
        awsIotClient.setNumOfClientThreads(2); // the same error occures when i didnt set this property... just tried to play with it a little
        try {
            logger.info("before awsIotClient.connect");
            awsIotClient.connect();
            logger.info("after awsIotClient.connect");
        } catch (AWSIotException e) {
            logger.error("error in connect from myMain", e);
            e.printStackTrace();
        }


        Timer timer = new Timer();

        timer.schedule( new TimerTask() {
            public void run() {
                logger.info("connection status = " + awsIotClient.getConnectionStatus().toString()); // prints CONNECTED every time, even when i disconnect from the internet
            }
        }, 0, 30*1000);

        // try to have a workaround
        timer.schedule( new TimerTask() {
            public void run() {
                try {
                    logger.info("will disconnect");
                    awsIotClient.disconnect();
                    logger.info("disconnected");
                } catch (AWSIotException e) {
                    logger.error("AWSIotException e , e = ", e);
                    e.printStackTrace();
                }
            }
        }, 0, 1000 * 60 * 10);

```

**Comment by 20matan** [comment]
I just want to say that it doesn't happen 100% of the times.
It usually happens when i launch the client, send some messages (let's say max 10), and after a while the client is not responding anymore...
It's pretty hard to detect&debug because it happens only sometimes

**Comment by justinboswell** [comment]
It's going to be near impossible to diagnose this without logs. Without knowing which side is hanging up, or what the order of operations is leading up to it, I am not going to be able to divine where the problem is coming from. The usual issues here are either the client being hung up on by being quiet for too long (MQTT keepalive), or the service is hanging up on the client after a message it doesn't like. In order to narrow it down, logs are going to be necessary.

**Comment by 20matan** [comment]
@justinboswell Ok, i'm using log4j for my logs, can you tell me how do i enable the logs for this library as well with log4j? i didn't find a way :/

Also, when i send a message every 1 minute (for example), then it works. i manually disconnect & reconnect with the code i sent in the previous comments, but it still listens to messages without problems (and if i send a 1-2 messages in 1-2 hours and then try to consume messages again, the consumer dont receive messages as explained above)

Could this help to you maybe to understand what is the problem?

**Comment by graebm** [comment]
I am not familiar with the log4j library. 

This library is logging messages with the default [Logger](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html) class. These logs are printed to the console by default.

**Comment by 20matan** [comment]
@graebm but the only logs that i get to the console are the "onConnectionSuccess" logs: 
```
Mar 19, 2019 4:27:26 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionSuccess
```

even when i run it with `java.util.logging.ConsoleHandler.level=ALL`. i don't get any more logs...
maybe i do something wrong (tried to follow the how to log in the README)

**Comment by 20matan** [comment]
Also, for every 30 seconds i printed the connection status.
even after the connection status was CONNECTED after the reconnection, not messages are received...
this is the log:

```
2019-03-19 16:34:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:34:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:35:06 INFO  TestTopicListener:37 - on message: 1553006106180
2019-03-19 16:35:10 INFO  TestTopicListener:37 - on message: 1553006110028
2019-03-19 16:35:11 INFO  TestTopicListener:37 - on message: 1553006111422
2019-03-19 16:35:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:35:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:36:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:36:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:37:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:37:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:38:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:38:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:39:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:39:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:40:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:40:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:41:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:41:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:42:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:42:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:43:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:43:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:44:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:44:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:45:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:45:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:46:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:46:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:47:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:47:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:48:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:48:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:49:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:49:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:50:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:50:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:51:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:51:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:52:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:52:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:53:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:53:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
Mar 19, 2019 4:54:18 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionFailure
INFO: Connection temporarily lost
Mar 19, 2019 4:54:18 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionFailure
INFO: Client connection lost: client-**************************
2019-03-19 16:54:18 INFO  PublishSubscribeSample:80 - connection status = DISCONNECTED
Mar 19, 2019 4:54:21 PM com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
Mar 19, 2019 4:54:22 PM com.amazonaws.services.iot.client.core.AwsIotConnection onConnectionSuccess
INFO: Connection successfully established
Mar 19, 2019 4:54:22 PM com.amazonaws.services.iot.client.core.AbstractAwsIotClient onConnectionSuccess
INFO: Client connection active: client-**************************
2019-03-19 16:54:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:55:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:55:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:56:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:56:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:57:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:57:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:58:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:58:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:59:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 16:59:48 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
2019-03-19 17:00:18 INFO  PublishSubscribeSample:80 - connection status = CONNECTED
// no more messages are received...
```

**Comment by graebm** [comment]
Due to the exact 20minute timing, this does seem very much like a "keepalive" issue.
The mqtt client automatically sends a ping to the server periodically, based on this value. If the server hasn't heard any activity from the client within some reasonable time the server will hang up on the client.

Are you calling `setKeepAliveInterval()`? Try setting it to something reasonable like 60000 (1 minute) before trying to connect.

**Comment by yaru10** [comment]
Still having same issue:( any one have solution ?

**Comment by yasminetalby** [comment]
Hello @yaru10 ,

I am sorry to hear that you are facing a similar issue.
Unfortunately, this issue was closed 3years ago due to inactivity from the original submitter. Your use case and experience might be different with changes made in the SDK since. Could you please open a new issue with detailed informations about your specific use case and behavior encountered?

I would also recommend using the V2 version of the SDK rather than this version. It is a complete rework, built to improve reliability, performance, and security: [aws-iot-device-sdk-v2](https://github.com/aws/aws-iot-device-sdk-java-v2). 

Best regards,

Yasmine

**Comment by jf-houndlabs** [comment]
I'm having  a similar issue my connection is interrupted and resumed every 30 mins - resume is very quick 

I set my connection for cleanSession to True - **when the interrupt happens I have to re-subscribe to the endpoints to have mqtt traffic work again** - if your clean session param is set to False on connection it should keep the subscribed endpoints - I want to come up clean and need to re-subscribe onResume with non-persistent session 

I have NOT found the source of the disconnect on my client end and I'm not responsible nor have access to the AWS broker and not sure how to see the ping responses. the 30mins disconnect is very consistent  

https://docs.aws.amazon.com/general/latest/gr/iot-core.html#message-broker-limits

looked over the sdk docs and the iot core aws setting for mqtt connection not sure why I get the disconnect. 

```

    auto onInterrupted = [&](Mqtt::MqttConnection &, int error) {
        qWarning() << "AWS " << __FUNCTION__  << "Connection interrupted with error:" << ErrorDebugString(error);
    };


    auto onResumed = [&](Mqtt::MqttConnection &, Mqtt::ReturnCode, bool) {
        qInfo() << "AWS " << __FUNCTION__  << "Connection resumed, mqtt return code:"; // << returnCode << "session present:" << sessionPresent;
        subscribe();
    };


    // Assign callbacks
    //
    connection->OnConnectionCompleted   = move(onConnectionCompleted);
    connection->OnDisconnect            = move(onDisconnect);
    connection->OnConnectionInterrupted = move(onInterrupted);
    connection->OnConnectionResumed     = move(onResumed);


    if (!connection->Connect(deviceID.toStdString().c_str(), true /*cleanSession*/, 60000 /*keepAliveTimeSecs*/, 30000 /*pingTimeoutMs*/))
    {
        qWarning() << "AWS " << __FUNCTION__ << "MQTT connection start failed with error" << ErrorDebugString(connection->LastError());
    }else{
        qInfo()<< "AWS " << __FUNCTION__ << "connected to:" << deviceID;
    }
```

**Comment by yasminetalby** [comment]
Hello @jf-houndlabs ,

Thank you very much for reaching out and sharing your use case.
Similarly to the question asked above by my colleague could you please provide the following information:
1. Logging information
2. AwsIotMqttClient set-up/configuration 
3. Are you calling setKeepAliveInterval() and following my colleagues recommendation above?

As mentioned above, without log information it is going to be complicated for us to find the root-cause of the issue. 

Thank you very much for your time and collaboration.

Sincerely,

Yasmine

**Comment by jf-houndlabs** [comment]
I don't have the logs or access to the broker side I think I determined the cause of the connection interruption

so the default time out is 20 mins (1200 seconds) on AWS side, and it waits for 1.5 times the default timeout which is 30 mins for it to disconnect 

I don't think there is anything that can be done besides re-scribe to endpoints if passing True for cleanSession (non persistent session)

**Comment by yaru10** [comment]
Thanks fellas! updating to sdk version 2 solved the problem.

вт, 11 июл. 2023 г. в 17:19, Yasmine Talby ***@***.***>:

**Comment by jmklix** [comment]
I'm glad you were able to get it working. Please let us know if you run into any other problems with this sdk
