### ISSUE TITLE
getRetryDelay() exponential backoff computation causes a Long overflow

### ISSUE THREAD

**Issue by amerello** [aws/aws-iot-device-sdk-java#92]
The way of calculating the exponential back-off delay in `AwsIotConnection.java` causes a Long overflow when the left side is bigger than 2^63-1, which isn't so hard to accomplish with that `Math.pow()`. 

If the baseRetryDelay=1[ms] and maxConnectionRetries>=63 that happens pretty fast ;)

```
return Math.min(client.getBaseRetryDelay() * (long) Math.pow(2, retryTimes), client.getMaxRetryDelay());
```

**Comment by justinboswell** [comment]
Good catch, thanks for the PR! I've approved and merged it.

**Comment by amerello** [comment]
Thank you for the quick merge!
