### ISSUE TITLE
Publish new patch release

### ISSUE THREAD

**Issue by amerello** [aws/aws-iot-device-sdk-java#94]
Hello guys/girls! Would it be possible to generate a new patch release (1.2.1 ?) and publish it? I'm particularly interested in getting the version with the already merged PR #93 available through an official maven repository. I'd be happy to help however I can with this.
Thanks!

**Comment by bretambrose** [comment]
We are working on getting a new release out, hopefully this week.

**Comment by ColdenCullen** [comment]
`v1.3.0` should work for you!
